export enum RoleType {
  SAAS_ADMIN = "SAAS_ADMIN",
  OWNER = "OWNER",
  MANAGER = "MANAGER",
  CASHIER = "CASHIER",
  // Legacy roles — kept for backward compatibility
  INVENTORY_ASSISTANT = "INVENTORY_ASSISTANT",
  ADMIN = "ADMIN",
  ACCOUNTANT = "ACCOUNTANT",
}

export enum UserStatus {
  PENDING_SETUP = "PENDING_SETUP",
  ACTIVE = "ACTIVE",
  DISABLED = "DISABLED",
  LOCKED = "LOCKED",
}

export enum AuthMethod {
  PASSWORD_TOTP = "PASSWORD_TOTP",
  PASSWORD_ONLY = "PASSWORD_ONLY",
  PIN_ONLY = "PIN_ONLY",
  OAUTH_GOOGLE = "OAUTH_GOOGLE",
}

export enum SessionStatus {
  ACTIVE = "ACTIVE",
  REVOKED = "REVOKED",
  EXPIRED = "EXPIRED",
}

export enum StepUpMethod {
  PIN = "PIN",
  REMOTE = "REMOTE",
  CODE = "CODE",
}

export enum StepUpStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  DENIED = "DENIED",
  EXPIRED = "EXPIRED",
}

export enum TwoFactorMethod {
  TOTP = "TOTP",
  BACKUP_CODE = "BACKUP_CODE",
}

export enum SaleType {
  FREE_SALE = "FREE_SALE",
  PRESCRIPTION = "PRESCRIPTION",
  CONTROLLED_SUBSTANCE = "CONTROLLED_SUBSTANCE",
}

export enum SaleOperationalState {
  IN_PROGRESS = "IN_PROGRESS",
  CONFIRMED = "CONFIRMED",
  ANNULLED = "ANNULLED",
  ABANDONED = "ABANDONED",
}

export enum FiscalDocumentType {
  INVOICE = "INVOICE",
  POS_TICKET = "POS_TICKET",
  CREDIT_NOTE = "CREDIT_NOTE",
  DEBIT_NOTE = "DEBIT_NOTE",
  SUPPORT_DOCUMENT = "SUPPORT_DOCUMENT",
}

export enum FiscalDocumentState {
  PENDING_GENERATION = "PENDING_GENERATION",
  PENDING_SIGNATURE = "PENDING_SIGNATURE",
  PENDING_TRANSMISSION = "PENDING_TRANSMISSION",
  VALIDATED = "VALIDATED",
  REJECTED = "REJECTED",
  CONTINGENCY = "CONTINGENCY",
}

export enum SyncStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
}

export enum IdentificationType {
  CC = "CC",
  NIT = "NIT",
  CE = "CE",
  PASSPORT = "PASSPORT",
  TI = "TI",
  PEP = "PEP",
}

export enum AuditAction {
  CREATE = "CREATE",
  READ = "READ",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  EXPORT = "EXPORT",
  IMPORT = "IMPORT",
  APPROVE = "APPROVE",
  ACCESS = "ACCESS",
  STATE_CHANGE = "STATE_CHANGE",
}

export enum SystemModule {
  AUTH = "AUTH",
  CATALOG = "CATALOG",
  INVENTORY = "INVENTORY",
  PURCHASES = "PURCHASES",
  SALES = "SALES",
  CASH_SHIFT = "CASH_SHIFT",
  FISCAL = "FISCAL",
  SYNC = "SYNC",
  CONFIG = "CONFIG",
  AUDIT = "AUDIT",
  CLIENTS = "CLIENTS",
  REPORTS = "REPORTS",
}

export enum PaymentMethodCategory {
  CASH = "CASH",
  CREDIT_CARD = "CREDIT_CARD",
  DEBIT_CARD = "DEBIT_CARD",
  CHECK = "CHECK",
  BANK_TRANSFER = "BANK_TRANSFER",
  DIGITAL_WALLET = "DIGITAL_WALLET",
  CREDIT = "CREDIT",
  OTHER = "OTHER",
}

export enum CashCountType {
  PARTIAL = "PARTIAL",
  CLOSING = "CLOSING",
}

export enum TaxSchemeType {
  IVA = "IVA",
  INC = "INC",
  RETEFUENTE = "RETEFUENTE",
  RETEICA = "RETEICA",
  IMPOCONSUMO = "IMPOCONSUMO",
  EXENTO = "EXENTO",
}
