/**
 * PrismaPGlite adapter integration tests for InventoryAdjustmentsService.
 *
 * These tests use the real PrismaClient connected to an in-memory PGlite via
 * the `pglite-prisma-adapter` package.
 *
 * ## Scope
 *
 * This test file verifies that `searchLots` works end-to-end through Prisma's
 * query engine and the adapter.  The `create` and `apply` methods are NOT
 * tested here because they call `tx.inventoryAdjustmentDocument.findFirst()`
 * — the `InventoryAdjustmentDocument` model is server-only and is absent from
 * the local PrismaClient generated by `@pharmacy/database/local`.
 *
 * ## Architectural finding
 *
 * `InventoryAdjustmentsService` depends on the `InventoryAdjustmentDocument`
 * model which is not in the local schema.  For the service to work with the
 * local-only PrismaClient, one of the following is needed:
 *
 * 1. Add `InventoryAdjustmentDocument` to the local schema (schema-source/shared)
 * 2. Refactor the service to avoid the dependency (e.g. use a local-only
 *    adjustment table or generate an in-memory sequential number)
 *
 * @vitest-environment node
 */
import {
  describe,
  expect,
  it,
  beforeAll,
  afterAll,
  vi,
} from "vitest";
import { PGlite } from "@electric-sql/pglite";
import { PrismaPGlite } from "pglite-prisma-adapter";
import { PrismaClient } from "@pharmacy/database/local";
import { LOCAL_SCHEMA_SQL } from "@pharmacy/database/local-schema";
import {
  InventoryAdjustmentsService,
  createInventoryAdjustmentsService,
} from "./inventory-adjustments.service";

// ---------------------------------------------------------------------------
// Setup
// ---------------------------------------------------------------------------

describe("InventoryAdjustmentsService — PrismaClient + PGlite integration", () => {
  let pg: PGlite;
  let prisma: PrismaClient;
  let service: InventoryAdjustmentsService;
  let auth: { requireRole: ReturnType<typeof vi.fn> };
  let productId: string;

  beforeAll(async () => {
    pg = new PGlite("memory://");
    await pg.exec(LOCAL_SCHEMA_SQL);

    const adapter = new PrismaPGlite(pg);
    prisma = new PrismaClient({ adapter });

    const now = new Date();
    productId = crypto.randomUUID();
    const userId = "user-int-01";

    // Seed product
    await prisma.product.create({
      data: {
        id: productId,
        internalCode: "INT-P001",
        commercialName: "Ibuprofeno 600mg",
        genericName: "Ibuprofeno",
        activePrinciple: "Ibuprofeno",
        laboratory: "Lab Integración",
        saleType: "FREE_SALE",
        isActive: true,
        createdAt: now,
        updatedAt: now,
        createdById: userId,
      },
    });

    // Seed two lots — one ACTIVE, one EXPIRED
    await prisma.lot.createMany({
      data: [
        {
          id: crypto.randomUUID(),
          batchNumber: "INT-B001",
          expirationDate: new Date("2027-12-31"),
          entryDate: new Date("2026-01-01"),
          state: "ACTIVE",
          currentStock: 100,
          version: 1,
          productId,
          locationCode: "EST-A1",
          createdAt: now,
          updatedAt: now,
        },
        {
          id: crypto.randomUUID(),
          batchNumber: "INT-B002",
          expirationDate: new Date("2025-01-01"),
          entryDate: new Date("2024-06-01"),
          state: "EXPIRED",
          currentStock: 0,
          version: 1,
          productId,
          locationCode: "EST-A2",
          createdAt: now,
          updatedAt: now,
        },
      ],
    });

    auth = { requireRole: vi.fn() };
    auth.requireRole.mockReturnValue({
      userId: "user-int-01",
      username: "integration",
      fullName: "Integration Tester",
      displayName: "Integration Tester",
      email: null,
      role: "INVENTORY_ASSISTANT",
      subscriptionId: null,
      workstationId: "ws-int-001",
      accessToken: "token",
      refreshToken: "refresh",
      expiresAt: new Date("2099-12-31"),
      sessionId: "sess-int-001",
      totpEnabled: false,
      avatarUrl: null,
      avatarColor: null,
      mustChangePassword: false,
    });
    service = createInventoryAdjustmentsService(prisma, auth as any);
  });

  afterAll(async () => {
    await prisma.$disconnect();
    await pg.close();
  });

  // -----------------------------------------------------------------------
  // searchLots — works through PrismaClient + PGlite adapter
  // -----------------------------------------------------------------------
  describe("searchLots", () => {
    it("finds lots by commercial name", async () => {
      const results = await service.searchLots("Ibuprofeno");

      expect(results).toHaveLength(1);
      expect(results[0].productName).toBe("Ibuprofeno 600mg");
      expect(results[0].currentStock).toBe(100);
      expect(results[0].lotCode).toBe("INT-B001");
    });

    it("finds lots by batch number", async () => {
      const results = await service.searchLots("INT-B001");

      expect(results).toHaveLength(1);
      expect(results[0].lotCode).toBe("INT-B001");
    });

    it("excludes non-ACTIVE lots from results", async () => {
      const results = await service.searchLots("INT-B002");

      // B002 is EXPIRED, so it should not be returned
      expect(results).toHaveLength(0);
    });

    it("returns empty array for non-matching query", async () => {
      const results = await service.searchLots("NONEXISTENT");

      expect(results).toEqual([]);
    });

    it("returns empty array for empty query", async () => {
      const results = await service.searchLots("");

      expect(results).toEqual([]);
    });

    it("returns lots ordered by expirationDate (ascending)", async () => {
      // Add a second ACTIVE lot with earlier expiry
      const now = new Date();
      await prisma.lot.create({
        data: {
          id: crypto.randomUUID(),
          batchNumber: "INT-B003",
          expirationDate: new Date("2026-06-01"),
          entryDate: new Date("2025-06-01"),
          state: "ACTIVE",
          currentStock: 50,
          version: 1,
          productId,
          locationCode: "EST-B1",
          createdAt: now,
          updatedAt: now,
        },
      });

      const results = await service.searchLots("Ibuprofeno");

      expect(results).toHaveLength(2);
      // First result should have earlier expiration
      expect(new Date(results[0].expirationDate).getTime()).toBeLessThan(
        new Date(results[1].expirationDate).getTime(),
      );
    });
  });

  // -----------------------------------------------------------------------
  // create and apply — NOT tested here (see architectural note above)
  // These methods depend on InventoryAdjustmentDocument which is server-only.
  // Unit tests in inventory-adjustments.service.test.ts cover the business
  // logic via mocked PrismaClient.
  // -----------------------------------------------------------------------
});
