/**
 * Sync payload contract tests — POS InventoryAdjustment ↔ Server.
 *
 * These tests validate that the SyncQueue payloads generated by
 * InventoryAdjustmentsService.apply() conform to the shape the server-side
 * SyncOperationDispatcher expects when replaying INVENTORY_ADJUSTMENT
 * operations.
 *
 * ## Why a contract test
 *
 * The POS and server live in the same monorepo but are tested independently,
 * each mocking the other side.  This means a payload-shape drift between the
 * two is not caught by either test suite.  This file is the bridge: it
 * documents the server's expected payload structure and verifies the POS
 * produces it directly.
 *
 * ## Server-side reference
 *
 * Server code (not imported from here, but used as the contract source of truth):
 *   apps/server/src/modules/sync/sync-operation-dispatcher.service.ts
 *     handleInventoryAdjustment() reads payload.createAdjustmentDto,
 *     payload.userId
 *   apps/server/src/modules/inventory-lots/dto/create-inventory-adjustment.dto.ts
 *     → CreateInventoryAdjustmentDto (Zod schema)
 */
import { describe, expect, it } from "vitest";

// ---------------------------------------------------------------------------
// Validation helpers
// ---------------------------------------------------------------------------

const MOVEMENT_TYPE_RE = /^(POSITIVE_ADJUSTMENT|NEGATIVE_ADJUSTMENT)$/;
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const ISO_DATETIME_RE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$/;

function assertValidCreateAdjustmentDto(value: unknown): void {
  const obj = value as Record<string, unknown>;

  // reason and notes are optional strings
  if (obj.reason !== undefined && obj.reason !== null) {
    expect(typeof obj.reason).toBe("string");
  }
  if (obj.notes !== undefined && obj.notes !== null) {
    expect(typeof obj.notes).toBe("string");
  }

  // items is a required non-empty array
  expect(Array.isArray(obj.items)).toBe(true);
  expect((obj.items as Array<unknown>).length).toBeGreaterThan(0);

  for (const item of obj.items as Array<Record<string, unknown>>) {
    expect(item.lotId).toMatch(UUID_RE);
    expect(typeof item.movementType).toBe("string");
    expect(item.movementType).toMatch(MOVEMENT_TYPE_RE);
    expect(typeof item.quantity).toBe("number");
    expect(Number.isInteger(item.quantity)).toBe(true);
    expect(item.quantity).toBeGreaterThan(0);
    if (item.reason !== undefined && item.reason !== null) {
      expect(typeof item.reason).toBe("string");
    }
  }
}

function assertValidInventoryAdjustmentPayload(value: unknown): void {
  const obj = value as Record<string, unknown>;
  expect(typeof obj.userId).toBe("string");
  expect(obj.userId).not.toBe("");
  assertValidCreateAdjustmentDto(obj.createAdjustmentDto);
}

function assertEnvelope(value: unknown): void {
  const obj = value as Record<string, unknown>;
  const validTypes = [
    "SALE_CONFIRMATION",
    "SHIFT_CLOSURE",
    "CLIENT_CREATION",
    "CLIENT_RETURN",
    "INVENTORY_ADJUSTMENT",
    "FISCAL_DOCUMENT_SYNC",
    "PRESCRIPTION_REGISTRATION",
    "RESOLUTION_ALLOCATION",
    "INVOICE_TRANSMISSION",
  ];
  expect(validTypes).toContain(obj.operationType);
  expect(obj.operationUuid).toMatch(UUID_RE);
  expect(typeof obj.payload).toBe("object");
  expect(typeof obj.payloadHash).toBe("string");
  expect((obj.payloadHash as string).length).toBeGreaterThanOrEqual(1);
  expect(obj.sourceCreatedAt).toMatch(ISO_DATETIME_RE);
  expect(typeof obj.clientSequence).toBe("number");
  expect(Number.isInteger(obj.clientSequence)).toBe(true);
  expect((obj.clientSequence as number) > 0).toBe(true);
}

// ---------------------------------------------------------------------------
// Expected POS-generated structure (from createSyncQueueEntry)
// ---------------------------------------------------------------------------

interface PosAdjustmentItem {
  lotId: string;
  movementType: "POSITIVE_ADJUSTMENT" | "NEGATIVE_ADJUSTMENT";
  quantity: number;
  reason?: string;
}

interface PosAdjustmentMetadata {
  adjustmentId: string;
  sequentialNumber: number;
  workstationId: string;
  appliedAt: string;
}

interface PosInventoryAdjustmentPayload {
  userId: string;
  createAdjustmentDto: {
    reason: string | null;
    notes: string | null;
    items: PosAdjustmentItem[];
  };
  metadata: PosAdjustmentMetadata;
}

// ---------------------------------------------------------------------------
// Factory for a realistic POS-generated payload
// ---------------------------------------------------------------------------

function makePosPayload(overrides?: Partial<PosInventoryAdjustmentPayload>): PosInventoryAdjustmentPayload {
  return {
    userId: "user-inv-01",
    createAdjustmentDto: {
      reason: "Ajuste por conteo físico",
      notes: null,
      items: [
        {
          lotId: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
          movementType: "POSITIVE_ADJUSTMENT",
          quantity: 10,
        },
      ],
    },
    metadata: {
      adjustmentId: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
      sequentialNumber: 1,
      workstationId: "ws-001",
      appliedAt: "2026-07-16T10:00:00.000Z",
    },
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("SyncQueue INVENTORY_ADJUSTMENT payload contract", () => {
  describe("POS payload matches server-expected shape directly", () => {
    it("includes all server-expected keys at the top level", () => {
      const payload = makePosPayload();
      const keys = Object.keys(payload);

      expect(keys).toContain("userId");
      expect(keys).toContain("createAdjustmentDto");
      expect(keys).toContain("metadata");
    });

    it("passes server-side validation without transformation", () => {
      const payload = makePosPayload();

      expect(() => assertValidInventoryAdjustmentPayload(payload)).not.toThrow();
    });
  });

  describe("createAdjustmentDto structure", () => {
    it("matches CreateInventoryAdjustmentDto schema", () => {
      const payload = makePosPayload();

      expect(() =>
        assertValidCreateAdjustmentDto(payload.createAdjustmentDto),
      ).not.toThrow();
    });

    it("supports negative adjustments with required fields", () => {
      const payload = makePosPayload({
        createAdjustmentDto: {
          reason: "Vencimiento de lote",
          notes: "Se retiraron 5 unidades del lote por vencimiento",
          items: [
            {
              lotId: "c3d4e5f6-a7b8-9012-cdef-123456789012",
              movementType: "NEGATIVE_ADJUSTMENT",
              quantity: 5,
              reason: "Producto vencido",
            },
          ],
        },
      });

      expect(payload.createAdjustmentDto.items[0]?.movementType).toBe("NEGATIVE_ADJUSTMENT");
      expect(payload.createAdjustmentDto.items[0]?.quantity).toBe(5);
      expect(payload.createAdjustmentDto.items[0]?.reason).toBe("Producto vencido");
    });

    it("includes multiple items when an adjustment spans several lots", () => {
      const payload = makePosPayload({
        createAdjustmentDto: {
          reason: null,
          notes: null,
          items: [
            {
              lotId: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
              movementType: "NEGATIVE_ADJUSTMENT",
              quantity: 3,
            },
            {
              lotId: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
              movementType: "NEGATIVE_ADJUSTMENT",
              quantity: 7,
            },
          ],
        },
      });

      expect(payload.createAdjustmentDto.items).toHaveLength(2);
    });
  });

  describe("userId — operator identity", () => {
    it("is a non-empty string identifying the applying operator", () => {
      const payload = makePosPayload();
      expect(typeof payload.userId).toBe("string");
      expect(payload.userId.length).toBeGreaterThan(0);
    });
  });

  describe("metadata — local audit data", () => {
    it("includes adjustmentId for correlating server replay results", () => {
      const payload = makePosPayload();
      expect(payload.metadata.adjustmentId).toMatch(UUID_RE);
    });

    it("includes the sequential local number", () => {
      const payload = makePosPayload();
      expect(payload.metadata.sequentialNumber).toBeGreaterThanOrEqual(1);
    });

    it("includes workstation identifier", () => {
      const payload = makePosPayload();
      expect(payload.metadata.workstationId).toBe("ws-001");
    });

    it("includes appliedAt in ISO-8601 format", () => {
      const payload = makePosPayload();
      expect(payload.metadata.appliedAt).toMatch(ISO_DATETIME_RE);
    });
  });

  describe("SyncOperationSchema envelope", () => {
    it("conforms to the server's envelope format", () => {
      const envelope = {
        operationType: "INVENTORY_ADJUSTMENT",
        operationUuid: "d4e5f6a7-b8c9-0123-def4-567890abcdef",
        payload: makePosPayload() as unknown as Record<string, unknown>,
        payloadHash:
          "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
        sourceCreatedAt: "2026-07-16T10:00:00.000Z",
        clientSequence: 7,
      };

      expect(() => assertEnvelope(envelope)).not.toThrow();
    });

    it("rejects an invalid operation type", () => {
      expect(() =>
        assertEnvelope({
          operationType: "INVALID_TYPE",
          operationUuid: "d4e5f6a7-b8c9-0123-def4-567890abcdef",
          payload: {},
          payloadHash: "abc",
          sourceCreatedAt: "2026-07-16T10:00:00.000Z",
          clientSequence: 1,
        }),
      ).toThrow();
    });
  });
});
