// Assemble a Prisma schema directory for a given target.
//
//   node scripts/assemble-schema.mjs full   → prisma/schema/         (shared + server-only)
//   node scripts/assemble-schema.mjs local  → prisma/schema-local/   (shared only)
//
// Each assembled directory gets:
//   schema.prisma      — generator + datasource blocks only
//   models/            — one file per source-fragment .prisma file
//
// Prisma 7 discovers models/ recursively when prisma.config.ts points
// `schema` at the parent directory (e.g. "./prisma/schema").
//
// The config is at packages/database/prisma.config.ts.

import { readFileSync, writeFileSync, mkdirSync, existsSync, rmSync } from 'node:fs';
import { readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SOURCE_DIR = join(ROOT, 'prisma', 'schema-source');

const SCHEMA_HEADER = (outputDir) => `// THIS FILE IS GENERATED BY scripts/assemble-schema.mjs — DO NOT EDIT.
// Edit the source files in prisma/schema-source/ instead.

generator client {
  provider = "prisma-client"
  output   = ${JSON.stringify(outputDir)}
}

datasource db {
  provider = "postgresql"
}
`;

/// Collect .prisma files from a source directory, excluding _header.prisma.
function collectPrismaFiles(sourceDir) {
  if (!existsSync(sourceDir)) return [];
  return readdirSync(sourceDir)
    .filter((f) => f.endsWith('.prisma') && f !== '_header.prisma')
    .sort(); // deterministic order
}

/// Read the content of a .prisma file and return it unchanged.
function readPrismaFile(sourceDir, file) {
  const src = join(sourceDir, file);
  return readFileSync(src, 'utf-8');
}

function assemble(target) {
  const isFull = target === 'full';
  const isLocal = target === 'local';

  if (!isFull && !isLocal) {
    console.error(`Unknown target: ${target}. Use "full" or "local".`);
    process.exit(1);
  }

  const destDir = isFull
    ? join(ROOT, 'prisma', 'schema')
    : join(ROOT, 'prisma', 'schema-local');
  const outputDir = isFull ? '../../generated/full-client' : '../../generated/local-client';

  console.log(`Assembling ${target} schema → ${destDir.replace(ROOT, '')}`);

  // Clean and recreate destination directory
  if (existsSync(destDir)) {
    rmSync(destDir, { recursive: true });
  }
  mkdirSync(destDir, { recursive: true });

  // Write schema.prisma — only generator + datasource blocks.
  // Prisma 7 discovers models/ recursively when prisma.config.ts
  // points schema at the parent directory.
  writeFileSync(join(destDir, 'schema.prisma'), SCHEMA_HEADER(outputDir), 'utf-8');

  // Create models/ subdirectory for all model/enum .prisma files
  const modelsDir = join(destDir, 'models');
  mkdirSync(modelsDir, { recursive: true });

  // Collect filenames from local-only to know which shared files to skip
  const localOnlyFiles = new Set(
    isLocal
      ? collectPrismaFiles(join(SOURCE_DIR, 'local-only'))
      : []
  );

  // 1. Shared files (skipping overrides for local target)
  const sharedDir = join(SOURCE_DIR, 'shared');
  for (const file of collectPrismaFiles(sharedDir)) {
    if (isLocal && localOnlyFiles.has(file)) {
      console.log(`  ~ ${file} (overridden by local-only)`);
      continue;
    }
    const dst = join(modelsDir, file);
    writeFileSync(dst, readPrismaFile(sharedDir, file), 'utf-8');
    console.log(`  + models/${file}`);
  }

  // 2. Server-only files (full target only)
  if (isFull) {
    const serverOnlyDir = join(SOURCE_DIR, 'server-only');
    for (const file of collectPrismaFiles(serverOnlyDir)) {
      const dst = join(modelsDir, file);
      writeFileSync(dst, readPrismaFile(serverOnlyDir, file), 'utf-8');
      console.log(`  + models/${file}`);
    }
  }

  // 3. Local-only override files (local target only)
  if (isLocal) {
    const localOnlyDir = join(SOURCE_DIR, 'local-only');
    for (const file of collectPrismaFiles(localOnlyDir)) {
      const dst = join(modelsDir, file);
      writeFileSync(dst, readPrismaFile(localOnlyDir, file), 'utf-8');
      console.log(`  + models/${file}`);
    }
  }

  console.log(`Done — ${target} schema ready at ${destDir.replace(ROOT, '')}/\n`);
}

const target = process.argv[2];
if (!target) {
  console.error('Usage: node scripts/assemble-schema.mjs <full|local>');
  process.exit(1);
}

assemble(target);
