// Assemble a Prisma schema directory for a given target.
//
//   node scripts/assemble-schema.mjs full   → prisma/schema/         (shared + server-only)
//   node scripts/assemble-schema.mjs local  → prisma/schema-local/   (shared only)
//
// Each assembled directory gets a schema.prisma with the appropriate generator output path,
// plus all .prisma files (except _header.prisma) from the source folders.

import { readFileSync, writeFileSync, mkdirSync, existsSync, rmSync } from 'node:fs';
import { readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SOURCE_DIR = join(ROOT, 'prisma', 'schema-source');

const SCHEMA_HEADER = (outputDir) => `// THIS FILE IS GENERATED BY scripts/assemble-schema.mjs — DO NOT EDIT.
// Edit the source files in prisma/schema-source/ instead.

generator client {
  provider = "prisma-client"
  output   = ${JSON.stringify(outputDir)}
}

datasource db {
  provider = "postgresql"
}
`;

function assemble(target) {
  const isFull = target === 'full';
  const isLocal = target === 'local';

  if (!isFull && !isLocal) {
    console.error(`Unknown target: ${target}. Use "full" or "local".`);
    process.exit(1);
  }

  const destDir = isFull
    ? join(ROOT, 'prisma', 'schema')
    : join(ROOT, 'prisma', 'schema-local');
  const outputDir = isFull ? '../../generated/full-client' : '../../generated/local-client';

  console.log(`Assembling ${target} schema → ${destDir.replace(ROOT, '')}`);

  // Clean and recreate destination directory
  if (existsSync(destDir)) {
    rmSync(destDir, { recursive: true });
  }
  mkdirSync(destDir, { recursive: true });

  // Write schema.prisma with the correct generator output
  writeFileSync(join(destDir, 'schema.prisma'), SCHEMA_HEADER(outputDir), 'utf-8');

  // Copy source .prisma files (excluding _header.prisma)
  const copySource = (sourceDir) => {
    if (!existsSync(sourceDir)) return;
    const files = readdirSync(sourceDir).filter(
      (f) => f.endsWith('.prisma') && f !== '_header.prisma'
    );
    for (const file of files) {
      const src = join(sourceDir, file);
      const dst = join(destDir, file);
      writeFileSync(dst, readFileSync(src, 'utf-8'), 'utf-8');
      console.log(`  + ${file}`);
    }
  };

  // Collect filenames from local-only to know which shared files to skip
  const localOnlyFiles = new Set(
    isLocal && existsSync(join(SOURCE_DIR, 'local-only'))
      ? readdirSync(join(SOURCE_DIR, 'local-only')).filter(
          (f) => f.endsWith('.prisma') && f !== '_header.prisma'
        )
      : []
  );

  // Copy shared files, skipping any that have a local-only override
  const sharedDir = join(SOURCE_DIR, 'shared');
  if (existsSync(sharedDir)) {
    const sharedFiles = readdirSync(sharedDir).filter(
      (f) => f.endsWith('.prisma') && f !== '_header.prisma'
    );
    for (const file of sharedFiles) {
      if (isLocal && localOnlyFiles.has(file)) {
        console.log(`  ~ ${file} (overridden by local-only)`);
        continue;
      }
      const src = join(sharedDir, file);
      const dst = join(destDir, file);
      writeFileSync(dst, readFileSync(src, 'utf-8'), 'utf-8');
      console.log(`  + ${file}`);
    }
  }

  if (isFull) {
    copySource(join(SOURCE_DIR, 'server-only'));
  }

  // Local-only override files (copied after shared to take precedence)
  if (isLocal) {
    copySource(join(SOURCE_DIR, 'local-only'));
  }

  console.log(`Done — ${target} schema ready at ${destDir.replace(ROOT, '')}/\n`);
}

const target = process.argv[2];
if (!target) {
  console.error('Usage: node scripts/assemble-schema.mjs <full|local>');
  process.exit(1);
}

assemble(target);
