/**
 * Local report export service.
 *
 * Generates PDF, Excel, CSV, and print payloads from a `ReportResponse`,
 * all without ever calling the server.  Excel uses SheetJS (`xlsx`),
 * CSV uses an in-house encoder that respects the Colombian Excel
 * conventions (UTF-8 BOM, `;` delimiter).  PDF generation uses jsPDF
 * with a minimal but legible table layout — the same chart image is
 * embedded when the report has a chart and the caller has rendered it
 * to a data URL via ECharts' `getDataURL`.
 *
 * All user-facing strings are i18n'd via the optional `t` function
 * on `ExportInput`.  When `t` is omitted the English/identifier fallback
 * is used, preserving backward compatibility.
 */

import * as XLSX from 'xlsx';
import { saveFileWithDialog } from '../../common/native-save';
import {
  ReportColumnType,
  ReportExportFormat,
  type AnyReportRow,
  type ReportColumn,
  type ReportDefinition,
  type ReportResponse,
} from './report-types';
import { getTenantInfo } from '../configuration/local-config.store';

const COL_DELIMITER = ';';
const BOM = '\uFEFF';

/**
 * Polyfill `SharedArrayBuffer` for jsPDF.
 *
 * jsPDF (via its `fflate` compression dependency) references
 * `SharedArrayBuffer` at module-import time.  In a webview without
 * cross-origin isolation headers the symbol is undefined, which
 * crashes the entire module load — even before any export button is
 * clicked, because the static import is evaluated eagerly.
 *
 * jsPDF uses `SharedArrayBuffer` only as a performance optimisation
 * inside `fflate`; `ArrayBuffer` provides the same API surface for
 * the subset that jsPDF actually calls (typed-array construction),
 * so substituting it here is safe.
 *
 * Call `ensureSharedArrayBuffer()` *before* the dynamic import.
 */
function ensureSharedArrayBuffer(): void {
  if (typeof globalThis.SharedArrayBuffer === 'undefined') {
    globalThis.SharedArrayBuffer = ArrayBuffer as unknown as typeof SharedArrayBuffer;
  }
}

export interface ExportInput {
  response: ReportResponse;
  definition: ReportDefinition;
  /** Format to render.  `print` produces a window.print() friendly HTML. */
  format: ReportExportFormat;
  /** When the report carries a chart, the ECharts data URL of the
   *  rendered image to embed in the PDF. */
  chartDataUrl?: string;
  /** Filename prefix (e.g. "sales-daily-summary").  The service
   *  appends the current date and the format extension. */
  filenamePrefix: string;
  /** Local user display name for the "Generated by" footer. */
  userDisplayName: string;
  /** Optional i18n translate function.  When omitted, English fallback
   *  strings are used (backward compatible). */
  t?: (key: string, fallback?: string) => string;
  /** Locale string for date/number formatting (default `'es-CO'`). */
  locale?: string;
  /** When true (default), opens the native OS save dialog (Tauri) or
   *  triggers a browser download (fallback).  Set false for scheduled /
   *  auto-generated exports that should save without user interaction —
   *  falls back to browser download in all environments. */
  showDialog?: boolean;
}

export class ReportExportService {
  /**
   * Render the export and save it.
   *
   * When `showDialog` is true (default), opens the native OS save dialog
   * (Tauri) or triggers a browser download (fallback).  Returns the saved
   * file path so the UI can show a success toast, or `null` when the user
   * cancelled the dialog.
   *
   * When `showDialog` is false (scheduled / auto-generated exports), uses
   * the browser download mechanism without user interaction.
   */
  async exportAndDownload(input: ExportInput): Promise<string | null> {
    const format = input.format;
    const showDialog = input.showDialog ?? true;

    if (format === 'print') {
      this.openPrintWindow(input);
      return null;
    }

    const filename = `${input.filenamePrefix}-${stampForFilename()}.${extForFormat(
      format,
    )}`;
    const filters: { name: string; extensions: string[] }[] = FILTER_MAP[format]
      ? [FILTER_MAP[format]!]
      : [];

    if (!showDialog) {
      // Scheduled / headless — use browser download (no native dialog).
      return this.exportWithoutDialog(format, filename, filters, input);
    }

    if (format === 'csv') {
      const content = this.renderCsv(input);
      return saveFileWithDialog({
        content,
        filename,
        mimeType: 'text/csv;charset=utf-8;',
        filters,
        title: input.t
          ? input.t('reports.exports.save_title', 'Guardar reporte CSV')
          : 'Guardar reporte CSV',
      });
    }
    if (format === 'excel') {
      const content = this.renderExcel(input);
      return saveFileWithDialog({
        content,
        filename,
        mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        filters,
        title: input.t
          ? input.t('reports.exports.save_title', 'Guardar reporte Excel')
          : 'Guardar reporte Excel',
      });
    }
    if (format === 'pdf') {
      const content = await this.renderPdf(input);
      return saveFileWithDialog({
        content,
        filename,
        mimeType: 'application/pdf',
        filters,
        title: input.t
          ? input.t('reports.exports.save_title', 'Guardar reporte PDF')
          : 'Guardar reporte PDF',
      });
    }

    throw new Error(`Unsupported export format: ${String(format)}`);
  }

  /** Browser-download fallback for scheduled exports (no dialog). */
  private async exportWithoutDialog(
    format: ReportExportFormat,
    filename: string,
    _filters: { name: string; extensions: string[] }[],
    input: ExportInput,
  ): Promise<string | null> {
    if (format === 'csv') {
      const csv = this.renderCsv(input);
      browserDownload(csv, filename, 'text/csv;charset=utf-8;');
    } else if (format === 'excel') {
      const buffer = this.renderExcel(input);
      browserDownloadBuffer(buffer, filename, 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    } else if (format === 'pdf') {
      const blob = await this.renderPdf(input);
      browserDownload(blob, filename, 'application/pdf');
    }
    return null;
  }

  /** Inline translate helper — returns the fallback when `t` is omitted. */
  private tr(t: ExportInput['t'], key: string, fallback: string): string {
    return t ? t(key, fallback) : fallback;
  }

  // -----------------------------------------------------------------------
  // CSV
  // -----------------------------------------------------------------------

  renderCsv(input: ExportInput): string {
    const { t } = input;
    const header = input.definition.columns
      .map((c) => escapeCsv(this.tr(t, c.titleKey, c.titleKey)))
      .join(COL_DELIMITER);
    const rows = input.response.rows.map((row) =>
      input.definition.columns
        .map((col) => escapeCsv(formatCell(row, col, input.locale)))
        .join(COL_DELIMITER),
    );
    return BOM + [header, ...rows].join('\r\n');
  }

  // -----------------------------------------------------------------------
  // Excel
  // -----------------------------------------------------------------------

  renderExcel(input: ExportInput): ArrayBuffer {
    const wb = XLSX.utils.book_new();
    const { t } = input;
    const loc = input.locale ?? 'es-CO';

    // Summary sheet — KPI cards.
    const summary = XLSX.utils.aoa_to_sheet([
      [this.tr(t, 'reports.export.report', 'Reporte'), input.definition.code],
      [this.tr(t, 'reports.export.generated_at', 'Generado'), new Date(input.response.generatedAt).toLocaleString(loc)],
      [this.tr(t, 'reports.export.user', 'Usuario'), input.userDisplayName],
      [this.tr(t, 'reports.export.source', 'Fuente'), this.tr(t, 'reports.export.local_source', 'Base de datos local del puesto de trabajo')],
      [],
      [this.tr(t, 'reports.export.kpi', 'KPI'), this.tr(t, 'reports.export.current_value', 'Valor actual'), this.tr(t, 'reports.export.previous_period', 'Período anterior')],
      ...input.response.kpis.map((kpi) => [
        this.tr(t, kpi.titleKey, kpi.titleKey),
        formatCellForExport(kpi.value, 'number', loc),
        formatCellForExport(kpi.previousValue ?? null, 'number', loc),
      ]),
    ]);
    XLSX.utils.book_append_sheet(wb, summary, this.tr(t, 'reports.export.summary_sheet', 'Resumen'));

    // Detail sheet — the paginated rows.
    const detailHeaders = input.definition.columns.map((c) =>
      this.tr(t, c.titleKey, c.titleKey),
    );
    const detailData = input.response.rows.map((row) =>
      input.definition.columns.map((col) => formatCellForExcel(row[col.id], col)),
    );
    const detail = XLSX.utils.aoa_to_sheet([detailHeaders, ...detailData]);

    // Auto-size columns — approximate widths based on content.
    const colWidths = input.definition.columns.map((_col, ci) => {
      const headerLen = detailHeaders[ci]?.length ?? 10;
      let maxLen = headerLen;
      for (const d of detailData) {
        const cell = d[ci];
        const len = cell != null ? String(cell).length : 0;
        if (len > maxLen) maxLen = len;
      }
      return { wch: Math.min(Math.max(maxLen + 2, 10), 50) };
    });
    detail['!cols'] = colWidths;
    XLSX.utils.book_append_sheet(wb, detail, this.tr(t, 'reports.export.detail_sheet', 'Detalle'));

    // Applied filters + freshness.
    const filters = XLSX.utils.aoa_to_sheet([
      [this.tr(t, 'reports.export.applied_filters', 'Filtros aplicados'), ''],
      [this.tr(t, 'reports.export.from', 'Desde'), input.response.filters.dateFrom],
      [this.tr(t, 'reports.export.to', 'Hasta'), input.response.filters.dateTo],
      [this.tr(t, 'reports.export.compare_previous', 'Comparar período anterior'), input.response.filters.comparePrevious ? this.tr(t, 'reports.export.yes', 'Sí') : this.tr(t, 'reports.export.no', 'No')],
      [],
      [this.tr(t, 'reports.export.data_freshness', 'Frescura de datos'), ''],
      [this.tr(t, 'reports.export.source', 'Fuente'), input.response.freshness.dataSource],
      [this.tr(t, 'reports.export.last_sync', 'Última sincronización'), input.response.freshness.lastSyncAt ?? '—'],
      [this.tr(t, 'reports.export.pending_operations', 'Operaciones pendientes'), String(input.response.freshness.pendingOperations)],
      [this.tr(t, 'reports.export.permanent_failures', 'Fallos permanentes'), String(input.response.freshness.permanentFailures)],
    ]);
    XLSX.utils.book_append_sheet(wb, filters, this.tr(t, 'reports.export.filters_sheet', 'Filtros'));

    return XLSX.write(wb, { type: 'array', bookType: 'xlsx' });
  }

  // -----------------------------------------------------------------------
  // PDF
  // -----------------------------------------------------------------------

  async renderPdf(input: ExportInput): Promise<string> {
    ensureSharedArrayBuffer();
    const { jsPDF } = await import('jspdf');
    const tenant = getTenantInfo();
    const doc = new jsPDF({ unit: 'pt', format: 'a4' });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 32;
    const usableWidth = pageWidth - margin * 2;
    const { t } = input;
    const loc = input.locale ?? 'es-CO';

    // --- Header — tenant identity ---
    doc.setFontSize(14);
    doc.text(tenant.name, margin, margin + 8);
    doc.setFontSize(9);
    let lineY = margin + 22;
    if (tenant.nit) { doc.text(`NIT: ${tenant.nit}`, margin, lineY); lineY += 12; }
    if (tenant.address) { doc.text(tenant.address, margin, lineY); lineY += 12; }

    // --- Title + filters ---
    doc.setFontSize(12);
    doc.text(input.definition.code, margin, lineY + 8);
    lineY += 22;
    doc.setFontSize(9);
    doc.text(
      `${this.tr(t, 'reports.export.from', 'Desde')} ${input.response.filters.dateFrom} ${this.tr(t, 'reports.export.to', 'hasta')} ${input.response.filters.dateTo}`,
      margin,
      lineY,
    );
    lineY += 12;
    doc.text(
      `${this.tr(t, 'reports.export.generated_at', 'Generado')}: ${new Date(input.response.generatedAt).toLocaleString(loc)}`,
      margin,
      lineY,
    );
    lineY += 12;
    doc.text(`${this.tr(t, 'reports.export.user', 'Usuario')}: ${input.userDisplayName}`, margin, lineY);
    lineY += 12;
    doc.text(this.tr(t, 'reports.export.source_label', 'Fuente: base de datos local del puesto de trabajo'), margin, lineY);
    lineY += 16;

    // --- KPI summary ---
    doc.setFontSize(10);
    doc.text(this.tr(t, 'reports.export.indicators', 'Indicadores'), margin, lineY);
    lineY += 12;
    doc.setFontSize(9);
    // Render KPIs in a compact 2-column layout to save vertical space.
    const kpiCol1 = margin;
    const kpiCol2 = margin + usableWidth / 2;
    input.response.kpis.forEach((kpi, idx) => {
      const x = idx % 2 === 0 ? kpiCol1 : kpiCol2;
      if (idx > 0 && idx % 2 === 0) lineY += 11;
      const label = this.tr(t, kpi.titleKey, kpi.titleKey);
      const val = formatCellForExport(kpi.value, 'number', loc);
      doc.text(`${label}: ${val}`, x, lineY);
    });
    lineY += (Math.ceil(input.response.kpis.length / 2) * 11) + 4;

    // --- Chart image (when provided) ---
    if (input.chartDataUrl) {
      lineY += 4;
      try {
        doc.addImage(input.chartDataUrl, 'PNG', margin, lineY, usableWidth, 180);
        lineY += 190;
      } catch {
        // Non-fatal.
      }
    }

    // --- Table ---
    if (input.response.rows.length === 0) {
      doc.setFontSize(9);
      doc.text(this.tr(t, 'reports.export.no_data', 'Sin datos para los filtros seleccionados.'), margin, lineY + 8);
    } else {
      lineY += 8;
      const columnDefs = input.definition.columns;

      // Proportional column widths based on type.
      const colWeights = columnDefs.map((col) => {
        switch (col.type) {
          case ReportColumnType.INTEGER:
          case ReportColumnType.NUMBER:
          case ReportColumnType.CURRENCY:
          case ReportColumnType.PERCENT:
            return 1;   // narrow
          case ReportColumnType.DATE:
            return 1.2;
          case ReportColumnType.DATETIME:
            return 1.5;
          case ReportColumnType.BADGE:
            return 1;
          default:
            return 3;   // text gets the most room
        }
      });
      const totalWeight = colWeights.reduce((a, b) => a + b, 0);
      const colWidths = colWeights.map((w) => (w / totalWeight) * usableWidth);

      // Translated headers.
      const headers = columnDefs.map((col) =>
        this.tr(t, col.titleKey, col.titleKey),
      );

      // Draw table header with background.
      const rowGap = 4;    // vertical padding within rows
      const minRowH = 11;  // minimum row height

      // Compute header height.
      const headerLines = headers.map((h) => doc.splitTextToSize(h, colWidths[headers.indexOf(h)] - rowGap * 2));
      const headerH = Math.max(minRowH, Math.max(...headerLines.map((l) => l.length * 5)) + rowGap * 2);

      // Check if header fits on current page; if not, new page.
      if (lineY + headerH > pageHeight - margin) {
        doc.addPage();
        lineY = margin;
      }

      // Draw header.
      doc.setFillColor(245, 245, 245);
      doc.rect(margin, lineY - headerH + rowGap, usableWidth, headerH, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      let xCursor = margin;
      headers.forEach((h, i) => {
        const lines = doc.splitTextToSize(h, colWidths[i] - rowGap * 2);
        lines.forEach((line: string, li: number) => {
          doc.text(line, xCursor + rowGap, lineY - headerH + rowGap + 4 + li * 5);
        });
        xCursor += colWidths[i];
      });
      doc.setFont('helvetica', 'normal');
      lineY += 3; // small gap below header

      // Data rows.
      const rows = input.response.rows;
      for (let ri = 0; ri < rows.length; ri++) {
        const row = rows[ri];

        // Format all cells for this row.
        const cellTexts = columnDefs.map((col) => formatCellForPdf(row, col, loc));

        // Compute required height for this row (tallest cell).
        let rowH = minRowH;
        xCursor = margin;
        columnDefs.forEach((_col, ci) => {
          const lines = doc.splitTextToSize(cellTexts[ci], colWidths[ci] - rowGap * 2);
          const needed = Math.max(minRowH, lines.length * 5 + rowGap * 2);
          if (needed > rowH) rowH = needed;
        });

        // Check page break.
        if (lineY + rowH > pageHeight - margin) {
          doc.addPage();
          lineY = margin;
          // Redraw header on new page.
          doc.setFillColor(245, 245, 245);
          doc.rect(margin, lineY - headerH + rowGap, usableWidth, headerH, 'F');
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(8);
          xCursor = margin;
          headers.forEach((h, i) => {
            const lines = doc.splitTextToSize(h, colWidths[i] - rowGap * 2);
            lines.forEach((line: string, li: number) => {
              doc.text(line, xCursor + rowGap, lineY - headerH + rowGap + 4 + li * 5);
            });
            xCursor += colWidths[i];
          });
          doc.setFont('helvetica', 'normal');
          lineY += 3;
        }

        // Draw cell content.
        doc.setFontSize(8);
        xCursor = margin;
        columnDefs.forEach((col, ci) => {
          const lines = doc.splitTextToSize(cellTexts[ci], colWidths[ci] - rowGap * 2);
          const align = col.align === 'right' ? 'right' : 'left';
          const cellX = align === 'right'
            ? xCursor + colWidths[ci] - rowGap
            : xCursor + rowGap;
          lines.forEach((line: string, li: number) => {
            doc.text(line, cellX, lineY + rowGap + 4 + li * 5, { align });
          });
          xCursor += colWidths[ci];
        });

        // Alternating row background.
        if (ri % 2 === 1) {
          doc.setFillColor(250, 250, 250);
          doc.rect(margin, lineY, usableWidth, rowH, 'F');
        }

        lineY += rowH;
      }
    }

    // --- Page numbers ---
    const pages = doc.getNumberOfPages();
    for (let p = 1; p <= pages; p++) {
      doc.setPage(p);
      doc.setFontSize(8);
      const pageLabel = this.tr(t, 'reports.export.page', 'Página');
      const ofLabel = this.tr(t, 'reports.export.of', 'de');
      doc.text(`${pageLabel} ${p} ${ofLabel} ${pages}`, pageWidth - margin, pageHeight - 12, {
        align: 'right',
      });
    }

    return doc.output();
  }

  // -----------------------------------------------------------------------
  // Print
  // -----------------------------------------------------------------------

  openPrintWindow(input: ExportInput): void {
    const html = this.renderPrintHtml(input);
    const win = window.open('', '_blank', 'noopener');
    if (!win) return;
    win.document.open();
    win.document.write(html);
    win.document.close();
    // Defer to the next frame so the user sees the rendered document
    // before the print dialog opens.
    win.requestAnimationFrame(() => win.print());
  }

  private renderPrintHtml(input: ExportInput): string {
    const tenant = getTenantInfo();
    const { t } = input;
    const loc = input.locale ?? 'es-CO';
    const headers = input.definition.columns
      .map((c) => `<th>${escapeHtml(this.tr(t, c.titleKey, c.titleKey))}</th>`)
      .join('');
    const body = input.response.rows
      .map(
        (row) =>
          `<tr>${input.definition.columns
            .map((col) => `<td>${escapeHtml(formatCell(row, col, loc))}</td>`)
            .join('')}</tr>`,
      )
      .join('');
    const kpis = input.response.kpis
      .map(
        (kpi) =>
          `<li><strong>${escapeHtml(this.tr(t, kpi.titleKey, kpi.titleKey))}:</strong> ${escapeHtml(
            formatCellForExport(kpi.value, 'number', loc),
          )}</li>`,
      )
      .join('');
    return `<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8">
<title>${escapeHtml(input.definition.code)}</title>
<style>
  body { font-family: 'Segoe UI', system-ui, sans-serif; color: #111; padding: 24px; }
  h1 { font-size: 18px; margin: 0 0 4px; }
  h2 { font-size: 14px; margin: 16px 0 6px; }
  .meta { font-size: 11px; color: #555; }
  table { width: 100%; border-collapse: collapse; margin-top: 12px; font-size: 11px; }
  th, td { border: 1px solid #ddd; padding: 4px 6px; text-align: left; }
  th { background: #f5f5f5; }
  ul { padding-left: 18px; font-size: 12px; }
</style>
</head>
<body>
  <h1>${escapeHtml(input.definition.code)}</h1>
  <div class="meta">
    <div>${escapeHtml(tenant.name)} ${tenant.nit ? `· NIT ${escapeHtml(tenant.nit)}` : ''}</div>
    <div>${this.tr(t, 'reports.export.from', 'Desde')} ${escapeHtml(input.response.filters.dateFrom)} ${this.tr(t, 'reports.export.to', 'hasta')} ${escapeHtml(input.response.filters.dateTo)}</div>
    <div>${this.tr(t, 'reports.export.generated_at', 'Generado')}: ${escapeHtml(new Date(input.response.generatedAt).toLocaleString(loc))}</div>
    <div>${this.tr(t, 'reports.export.user', 'Usuario')}: ${escapeHtml(input.userDisplayName)}</div>
    <div><em>${this.tr(t, 'reports.export.source_label', 'Fuente: base de datos local del puesto de trabajo')}</em></div>
  </div>
  <h2>${this.tr(t, 'reports.export.indicators', 'Indicadores')}</h2>
  <ul>${kpis}</ul>
  <h2>${this.tr(t, 'reports.export.detail', 'Detalle')}</h2>
  <table>
    <thead><tr>${headers}</tr></thead>
    <tbody>${body || `<tr><td colspan="100%">${this.tr(t, 'reports.export.no_data', 'Sin datos para los filtros seleccionados.')}</td></tr>`}</tbody>
  </table>
</body>
</html>`;
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function extForFormat(format: ReportExportFormat): string {
  if (format === 'excel') return 'xlsx';
  if (format === 'pdf') return 'pdf';
  if (format === 'csv') return 'csv';
  return 'html';
}

function stampForFilename(): string {
  return new Date().toISOString().replace(/[:.]/gu, '-').slice(0, 19);
}

function escapeCsv(value: string): string {
  // CSV with `;` delimiter.  Quotes are doubled, the whole cell is
  // quoted when it contains the delimiter, a quote, a CR or an LF.
  if (value === '') return '';
  if (/[";\r\n]/u.test(value)) {
    return `"${value.replace(/"/gu, '""')}"`;
  }
  return value;
}

function formatCell(row: AnyReportRow, col: ReportColumn, locale?: string): string {
  const loc = locale ?? 'es-CO';
  const raw = row[col.id];
  if (raw === null || raw === undefined) return '';
  switch (col.type) {
    case ReportColumnType.CURRENCY:
      return Number(raw).toLocaleString(loc, { style: 'currency', currency: 'COP' });
    case ReportColumnType.PERCENT:
      return `${Number(raw).toFixed(2)}%`;
    case ReportColumnType.INTEGER:
      return Number(raw).toLocaleString(loc);
    case ReportColumnType.NUMBER:
      return Number(raw).toLocaleString(loc, { maximumFractionDigits: 4 });
    case ReportColumnType.DATE:
    case ReportColumnType.DATETIME: {
      const d = new Date(raw as string);
      if (Number.isNaN(d.getTime())) return String(raw);
      if (col.type === ReportColumnType.DATE) {
        return d.toLocaleDateString(loc);
      }
      return d.toLocaleString(loc);
    }
    default:
      return String(raw);
  }
}

function formatCellForExport(
  value: string | number | null | undefined,
  _unit: string,
  locale?: string,
): string {
  const loc = locale ?? 'es-CO';
  if (value === null || value === undefined) return '';
  if (typeof value === 'number') {
    return value.toLocaleString(loc, { maximumFractionDigits: 4 });
  }
  return String(value);
}

/**
 * Format a cell value for PDF output, avoiding locale characters that
 * jsPDF's built-in Helvetica font cannot render.
 *
 * Currency es-CO produces a non-breaking space between $ and amount;
 * Helvetica renders that as "Â".  We use a plain "$" + formatted number
 * instead.  Numbers use periods as thousand separators (Colombian style)
 * and commas for decimals where applicable.
 */
function formatCellForPdf(row: AnyReportRow, col: ReportColumn, locale?: string): string {
  const raw = row[col.id];
  if (raw === null || raw === undefined) return '';
  switch (col.type) {
    case ReportColumnType.CURRENCY: {
      const n = Number(raw);
      if (n === 0) return '$0';
      const intl = n.toLocaleString(locale ?? 'es-CO', { maximumFractionDigits: 0 });
      return `$${intl}`;
    }
    case ReportColumnType.PERCENT:
      return `${Number(raw).toFixed(2)}%`;
    case ReportColumnType.INTEGER:
      return Number(raw).toLocaleString(locale ?? 'es-CO');
    case ReportColumnType.NUMBER:
      return Number(raw).toLocaleString(locale ?? 'es-CO', { maximumFractionDigits: 4 });
    case ReportColumnType.DATE:
    case ReportColumnType.DATETIME: {
      const d = new Date(raw as string);
      if (Number.isNaN(d.getTime())) return String(raw);
      if (col.type === ReportColumnType.DATE) return d.toLocaleDateString(locale ?? 'es-CO');
      return d.toLocaleString(locale ?? 'es-CO');
    }
    default:
      return String(raw);
  }
}

function formatCellForExcel(value: unknown, col: ReportColumn): string | number | Date {
  if (value === null || value === undefined) return '';
  if (col.type === ReportColumnType.INTEGER) return Number(value);
  if (col.type === ReportColumnType.NUMBER) return Number(value);
  if (col.type === ReportColumnType.CURRENCY) return Number(value);
  if (col.type === ReportColumnType.PERCENT) return Number(value);
  if (col.type === ReportColumnType.DATE || col.type === ReportColumnType.DATETIME) {
    return new Date(value as string);
  }
  return String(value);
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/gu, '&amp;')
    .replace(/</gu, '&lt;')
    .replace(/>/gu, '&gt;')
    .replace(/"/gu, '&quot;');
}

// Map export format → save-dialog file filter for the native dialog.
const FILTER_MAP: Record<string, { name: string; extensions: string[] } | null> = {
  csv: { name: 'CSV', extensions: ['csv'] },
  excel: { name: 'Excel', extensions: ['xlsx'] },
  pdf: { name: 'PDF', extensions: ['pdf'] },
  print: null,
};

// ---------------------------------------------------------------------------
// Browser-download fallback helpers (for scheduled / non-interactive exports)
// ---------------------------------------------------------------------------

function browserDownload(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

function browserDownloadBuffer(buffer: ArrayBuffer, filename: string, mimeType: string): void {
  const blob = new Blob([buffer], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}
