/**
 * Sync payload contract tests — POS ClientCreation ↔ Server.
 *
 * These tests validate that the SyncQueue payloads generated by
 * ClientsService.create() conform to the shape the server-side
 * SyncOperationDispatcher expects when replaying CLIENT_CREATION operations.
 *
 * ## Server-side reference
 *
 * Server code (not imported from here, but used as the contract source of truth):
 *   apps/server/src/modules/sync/sync-operation-dispatcher.service.ts
 *     handleClientCreation() reads payload.userId, payload.createClientDto,
 *     payload.localClientId
 *   apps/server/src/modules/clients/dto/create-client.dto.ts → CreateClientDto
 *
 * @note If you change the POS's createSyncQueueEntry payload shape, update the
 *       expected shapes below AND verify against the server's dispatcher.
 */
import { describe, expect, it } from "vitest";

// ---------------------------------------------------------------------------
// Validation helpers
// ---------------------------------------------------------------------------

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const IDENTIFICATION_TYPE_RE = /^(CC|NIT|CE|PASSPORT|TI|PEP)$/;
const ISO_DATETIME_RE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$/;

function assertValidCreateClientDto(value: unknown): void {
  const obj = value as Record<string, unknown>;

  expect(typeof obj.fullName).toBe("string");
  expect((obj.fullName as string).length).toBeGreaterThan(0);

  expect(typeof obj.identificationType).toBe("string");
  expect(obj.identificationType).toMatch(IDENTIFICATION_TYPE_RE);

  expect(typeof obj.identificationNumber).toBe("string");
  expect((obj.identificationNumber as string).length).toBeGreaterThan(0);

  // Optional fields — must be string when present, null otherwise
  for (const field of ["email", "phone", "address", "municipality", "department"]) {
    if (obj[field] !== null && obj[field] !== undefined) {
      expect(typeof obj[field]).toBe("string");
    }
  }
}

function assertValidClientCreationPayload(value: unknown): void {
  const obj = value as Record<string, unknown>;

  expect(typeof obj.userId).toBe("string");
  expect((obj.userId as string).length).toBeGreaterThan(0);

  assertValidCreateClientDto(obj.createClientDto);

  // Must carry metadata for server-side correlation
  const metadata = obj.metadata as Record<string, unknown> | undefined;
  expect(metadata).toBeDefined();
  expect(typeof metadata?.localClientId).toBe("string");
  expect((metadata?.localClientId as string)).toMatch(UUID_RE);
  expect(typeof metadata?.workstationId).toBe("string");
  expect((metadata?.workstationId as string).length).toBeGreaterThan(0);
  expect(typeof metadata?.createdAt).toBe("string");
  expect((metadata?.createdAt as string)).toMatch(ISO_DATETIME_RE);
}

function assertEnvelope(value: unknown): void {
  const obj = value as Record<string, unknown>;
  const validTypes = [
    "SALE_CONFIRMATION",
    "SHIFT_CLOSURE",
    "CLIENT_CREATION",
    "CLIENT_RETURN",
    "INVENTORY_ADJUSTMENT",
    "FISCAL_DOCUMENT_SYNC",
    "PRESCRIPTION_REGISTRATION",
    "RESOLUTION_ALLOCATION",
    "INVOICE_TRANSMISSION",
  ];
  expect(validTypes).toContain(obj.operationType);
  expect(obj.operationUuid).toMatch(UUID_RE);
  expect(typeof obj.payload).toBe("object");
  expect(typeof obj.payloadHash).toBe("string");
  expect((obj.payloadHash as string).length).toBeGreaterThanOrEqual(1);
  expect(obj.sourceCreatedAt).toMatch(ISO_DATETIME_RE);
  expect(typeof obj.clientSequence).toBe("number");
  expect(Number.isInteger(obj.clientSequence)).toBe(true);
  expect((obj.clientSequence as number) > 0).toBe(true);
}

// ---------------------------------------------------------------------------
// Expected POS-generated structure (from createSyncQueueEntry)
// ---------------------------------------------------------------------------

interface PosClientCreationPayload {
  createClientDto: {
    fullName: string;
    identificationType: string;
    identificationNumber: string;
    email: string | null;
    phone: string | null;
    address: string | null;
    municipality: string | null;
    department: string | null;
  };
  userId: string;
  metadata: {
    localClientId: string;
    workstationId: string;
    createdAt: string;
  };
}

// ---------------------------------------------------------------------------
// Factory for a realistic POS-generated payload
// ---------------------------------------------------------------------------

function makePosPayload(
  overrides?: Partial<PosClientCreationPayload>,
): PosClientCreationPayload {
  return {
    createClientDto: {
      fullName: "Juan Pérez",
      identificationType: "CC",
      identificationNumber: "1234567890",
      email: "juan@example.com",
      phone: "+573001234567",
      address: "Calle 123 #45-67",
      municipality: "Medellín",
      department: "Antioquia",
    },
    userId: "user-cashier-01",
    metadata: {
      localClientId: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
      workstationId: "ws-001",
      createdAt: "2026-07-16T10:00:00.000Z",
    },
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("SyncQueue CLIENT_CREATION payload contract", () => {
  describe("POS payload matches server-expected shape directly", () => {
    it("includes all server-expected keys at the top level", () => {
      const payload = makePosPayload();
      const keys = Object.keys(payload);

      expect(keys).toContain("userId");
      expect(keys).toContain("createClientDto");
      expect(keys).toContain("metadata");
    });

    it("passes server-side validation without transformation", () => {
      const payload = makePosPayload();

      expect(() =>
        assertValidClientCreationPayload(payload),
      ).not.toThrow();
    });
  });

  describe("createClientDto structure", () => {
    it("matches CreateClientDto schema", () => {
      const payload = makePosPayload();

      expect(() =>
        assertValidCreateClientDto(payload.createClientDto),
      ).not.toThrow();
    });

    it("accepts minimum fields with optional fields as null", () => {
      const payload = makePosPayload({
        createClientDto: {
          fullName: "Carlos Méndez",
          identificationType: "CC",
          identificationNumber: "987654321",
          email: null,
          phone: null,
          address: null,
          municipality: null,
          department: null,
        },
      });

      expect(() =>
        assertValidCreateClientDto(payload.createClientDto),
      ).not.toThrow();
    });
  });

  describe("userId — operator identity", () => {
    it("is a non-empty string identifying the creating operator", () => {
      const payload = makePosPayload();
      expect(typeof payload.userId).toBe("string");
      expect(payload.userId.length).toBeGreaterThan(0);
    });
  });

  describe("metadata — local audit data", () => {
    it("includes localClientId for correlating server-side records", () => {
      const payload = makePosPayload();
      expect(payload.metadata.localClientId).toMatch(UUID_RE);
    });

    it("includes workstation identifier", () => {
      const payload = makePosPayload();
      expect(payload.metadata.workstationId).toBe("ws-001");
    });

    it("includes createdAt in ISO-8601 format", () => {
      const payload = makePosPayload();
      expect(payload.metadata.createdAt).toMatch(ISO_DATETIME_RE);
    });
  });

  describe("SyncOperationSchema envelope", () => {
    it("conforms to the server's envelope format", () => {
      const envelope = {
        operationType: "CLIENT_CREATION",
        operationUuid: "b0a1b2c3-d4e5-6789-0abc-def123456789",
        payload: makePosPayload() as unknown as Record<string, unknown>,
        payloadHash:
          "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
        sourceCreatedAt: "2026-07-16T10:00:00.000Z",
        clientSequence: 42,
      };

      expect(() => assertEnvelope(envelope)).not.toThrow();
    });

    it("rejects an invalid operation type", () => {
      expect(() =>
        assertEnvelope({
          operationType: "INVALID_TYPE",
          operationUuid: "b0a1b2c3-d4e5-6789-0abc-def123456789",
          payload: {},
          payloadHash: "abc",
          sourceCreatedAt: "2026-07-16T10:00:00.000Z",
          clientSequence: 1,
        }),
      ).toThrow();
    });
  });
});
