/**
 * Sync payload contract tests — POS ClientCreditPayment ↔ Server.
 *
 * These tests validate that the SyncQueue payloads generated by
 * CreditService.recordCreditPayment() conform to the shape the server-side
 * SyncOperationDispatcher expects when replaying CLIENT_CREDIT_PAYMENT
 * operations.
 *
 * ## Server-side reference
 *
 * Server code (not imported from here, but used as the contract source of truth):
 *   apps/server/src/modules/sync/sync-operation-dispatcher.service.ts
 *     handleClientCreditPayment() reads payload.paymentId,
 *     payload.metadata.localPaymentId, payload.clientId,
 *     payload.sequentialNumber, payload.amount, payload.paymentMethodId,
 *     payload.notes, payload.createdById, payload.cashShiftId,
 *     payload.workstationId, payload.metadata.createdAt
 *
 * @note If you change the POS's createSyncQueueEntry payload shape, update the
 *       expected shapes below AND verify against the server's dispatcher.
 */
import { describe, expect, it } from "vitest";

// ---------------------------------------------------------------------------
// Validation helpers
// ---------------------------------------------------------------------------

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const DECIMAL_RE = /^\d+(\.\d{1,2})?$/;
const ISO_DATETIME_RE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$/;

/** The exact shape CreditService.recordCreditPayment() puts on the queue. */
interface ClientCreditPaymentPayload {
  paymentId: string;
  sequentialNumber: number;
  clientId: string;
  amount: string;
  paymentMethodId: string;
  notes: string | null;
  createdById: string;
  cashShiftId: string;
  workstationId: string;
  metadata: {
    localPaymentId: string;
    workstationId: string;
    createdAt: string;
  };
}

function assertValidClientCreditPaymentPayload(value: unknown): void {
  const obj = value as ClientCreditPaymentPayload;

  // Identifiers the server reads directly
  expect(obj.paymentId).toMatch(UUID_RE);
  expect(obj.clientId).toMatch(UUID_RE);
  expect(obj.paymentMethodId).toMatch(UUID_RE);
  expect(obj.createdById).toMatch(UUID_RE);
  expect(obj.cashShiftId).toMatch(UUID_RE);
  expect(obj.workstationId).toMatch(UUID_RE);

  // Sequential counter + amount (decimal string, e.g. "500.00")
  expect(Number.isInteger(obj.sequentialNumber)).toBe(true);
  expect(obj.sequentialNumber).toBeGreaterThan(0);
  expect(obj.amount).toMatch(DECIMAL_RE);

  // Notes are optional
  expect(obj.notes === null || typeof obj.notes === "string").toBe(true);

  // Metadata — the server falls back to metadata.localPaymentId for the id
  expect(obj.metadata.localPaymentId).toMatch(UUID_RE);
  expect(obj.metadata.localPaymentId).toBe(obj.paymentId);
  expect(obj.metadata.workstationId).toMatch(UUID_RE);
  expect(obj.metadata.createdAt).toMatch(ISO_DATETIME_RE);
}

function buildPaymentPayload(
  overrides: Partial<ClientCreditPaymentPayload> = {},
): ClientCreditPaymentPayload {
  const id = "11111111-1111-4111-8111-111111111111";
  return {
    paymentId: id,
    sequentialNumber: 1,
    clientId: "22222222-2222-4222-8222-222222222222",
    amount: "500.00",
    paymentMethodId: "33333333-3333-4333-8333-333333333333",
    notes: "Primer abono",
    createdById: "44444444-4444-4444-8444-444444444444",
    cashShiftId: "55555555-5555-4555-8555-555555555555",
    workstationId: "66666666-6666-4666-8666-666666666666",
    metadata: {
      localPaymentId: id,
      workstationId: "66666666-6666-4666-8666-666666666666",
      createdAt: "2026-07-24T09:00:00.000Z",
    },
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Suite
// ---------------------------------------------------------------------------

describe("CLIENT_CREDIT_PAYMENT sync payload contract", () => {
  it("accepts the payload shape CreditService.recordCreditPayment builds", () => {
    const payload = buildPaymentPayload();
    expect(() => assertValidClientCreditPaymentPayload(payload)).not.toThrow();
  });

  it("accepts a null notes field (no note entered)", () => {
    const payload = buildPaymentPayload({ notes: null });
    expect(() => assertValidClientCreditPaymentPayload(payload)).not.toThrow();
  });

  it("exposes every key the server dispatcher reads", () => {
    const payload = buildPaymentPayload();
    const obj = payload as unknown as Record<string, unknown>;

    // Keys read directly by handleClientCreditPayment
    expect(obj.paymentId).toBeDefined();
    expect(obj.sequentialNumber).toBeDefined();
    expect(obj.clientId).toBeDefined();
    expect(obj.amount).toBeDefined();
    expect(obj.paymentMethodId).toBeDefined();
    expect(obj.notes).toBeDefined();
    expect(obj.createdById).toBeDefined();
    expect(obj.cashShiftId).toBeDefined();
    expect(obj.workstationId).toBeDefined();
    // Metadata keys (localPaymentId + createdAt)
    expect(payload.metadata.localPaymentId).toBeDefined();
    expect(payload.metadata.createdAt).toBeDefined();
  });

  it("rejects a malformed amount (float precision bug guard)", () => {
    const payload = buildPaymentPayload({ amount: "500.44999999999999" });
    expect(() => assertValidClientCreditPaymentPayload(payload)).toThrow();
  });
});

// ---------------------------------------------------------------------------
// CLIENT_CREDIT_PAYMENT_ANNULMENT contract
// ---------------------------------------------------------------------------

/** The exact shape CreditService.annulCreditPayment() puts on the queue. */
interface ClientCreditPaymentAnnulmentPayload {
  paymentId: string;
  clientId: string;
  annulmentReason: string;
  annulledById: string;
  annulledAt: string;
  metadata: {
    localPaymentId: string;
    workstationId: string;
    annulledAt: string;
  };
}

function assertValidAnnulmentPayload(value: unknown): void {
  const obj = value as ClientCreditPaymentAnnulmentPayload;

  expect(obj.paymentId).toMatch(UUID_RE);
  expect(obj.clientId).toMatch(UUID_RE);
  expect(obj.annulledById).toMatch(UUID_RE);

  // Mandatory reason + ISO annulment timestamp
  expect(obj.annulmentReason.length).toBeGreaterThan(0);
  expect(obj.annulledAt).toMatch(ISO_DATETIME_RE);

  // Metadata — the server falls back to metadata.localPaymentId for the id
  expect(obj.metadata.localPaymentId).toMatch(UUID_RE);
  expect(obj.metadata.localPaymentId).toBe(obj.paymentId);
  expect(obj.metadata.workstationId).toMatch(UUID_RE);
  expect(obj.metadata.annulledAt).toMatch(ISO_DATETIME_RE);
}

function buildAnnulmentPayload(
  overrides: Partial<ClientCreditPaymentAnnulmentPayload> = {},
): ClientCreditPaymentAnnulmentPayload {
  const id = "11111111-1111-4111-8111-111111111111";
  return {
    paymentId: id,
    clientId: "22222222-2222-4222-8222-222222222222",
    annulmentReason: "Registro duplicado",
    annulledById: "44444444-4444-4444-8444-444444444444",
    annulledAt: "2026-07-25T11:00:00.000Z",
    metadata: {
      localPaymentId: id,
      workstationId: "66666666-6666-4666-8666-666666666666",
      annulledAt: "2026-07-25T11:00:00.000Z",
    },
    ...overrides,
  };
}

describe("CLIENT_CREDIT_PAYMENT_ANNULMENT sync payload contract", () => {
  it("accepts the payload shape CreditService.annulCreditPayment builds", () => {
    const payload = buildAnnulmentPayload();
    expect(() => assertValidAnnulmentPayload(payload)).not.toThrow();
  });

  it("exposes every key the server dispatcher reads", () => {
    const payload = buildAnnulmentPayload();
    const obj = payload as unknown as Record<string, unknown>;

    // Keys read directly by handleClientCreditPaymentAnnulment
    expect(obj.paymentId).toBeDefined();
    expect(obj.clientId).toBeDefined();
    expect(obj.annulmentReason).toBeDefined();
    expect(obj.annulledById).toBeDefined();
    expect(obj.annulledAt).toBeDefined();
    // Metadata keys (localPaymentId + annulledAt)
    expect(payload.metadata.localPaymentId).toBeDefined();
    expect(payload.metadata.annulledAt).toBeDefined();
  });

  it("rejects a missing annulment reason (mandatory-reason guard)", () => {
    const payload = buildAnnulmentPayload({ annulmentReason: "" });
    expect(() => assertValidAnnulmentPayload(payload)).toThrow();
  });
});
