/**
 * Sync payload contract tests — POS Purchase operations ↔ Server.
 *
 * Validates that the SyncQueue payloads generated by the purchase services
 * conform to the shapes the server-side SyncOperationDispatcher expects
 * when replaying PURCHASE_ORDER_CONFIRMATION, PURCHASE_RECEPTION_CONFIRMATION,
 * and SUPPLIER_RETURN_CONFIRMATION operations.
 *
 * ## Why a contract test
 *
 * The POS and server live in the same monorepo but are tested independently.
 * This file documents the server's expected payload structure and verifies
 * the POS produces it.
 */
import { describe, expect, it } from 'vitest';

// ---------------------------------------------------------------------------
// Validation helpers
// ---------------------------------------------------------------------------

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const ISO_DATETIME_RE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$/;

// ---------------------------------------------------------------------------
// POS-generated payload interfaces (mirrors sync-types.ts)
// ---------------------------------------------------------------------------

interface PosPurchaseOrderPayload {
  operationType: 'PURCHASE_ORDER_CONFIRMATION';
  orderId: string;
  sequentialNumber: number;
  supplierId: string;
  notes: string | null;
  createdById: string;
  confirmedByUserId: string;
  workstationId: string;
  confirmedAt: string;
  metadata: {
    localOrderId: string;
    workstationId: string;
    confirmedAt: string;
  };
}

interface PosPurchaseReceptionPayload {
  operationType: 'PURCHASE_RECEPTION_CONFIRMATION';
  receptionId: string;
  sequentialNumber: number;
  supplierId: string;
  purchaseOrderId: string | null;
  notes: string | null;
  createdById: string;
  confirmedByUserId: string;
  workstationId: string;
  confirmedAt: string;
  metadata: {
    localReceptionId: string;
    workstationId: string;
    confirmedAt: string;
  };
}

interface PosSupplierReturnPayload {
  operationType: 'SUPPLIER_RETURN_CONFIRMATION';
  returnId: string;
  sequentialNumber: number;
  supplierId: string;
  purchaseReceptionId: string | null;
  reason: string | null;
  createdByUserId: string;
  workstationId: string;
  confirmedAt: string;
  metadata: {
    localReturnId: string;
    workstationId: string;
    confirmedAt: string;
  };
}

// ---------------------------------------------------------------------------
// Factories
// ---------------------------------------------------------------------------

function makePurchaseOrderPayload(
  overrides?: Partial<PosPurchaseOrderPayload>,
): PosPurchaseOrderPayload {
  return {
    operationType: 'PURCHASE_ORDER_CONFIRMATION',
    orderId: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    sequentialNumber: 1,
    supplierId: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    notes: 'Pedido urgente',
    createdById: 'user-inv-01',
    confirmedByUserId: 'user-inv-01',
    workstationId: 'ws-001',
    confirmedAt: '2026-07-16T10:00:00.000Z',
    metadata: {
      localOrderId: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
      workstationId: 'ws-001',
      confirmedAt: '2026-07-16T10:00:00.000Z',
    },
    ...overrides,
  };
}

function makePurchaseReceptionPayload(
  overrides?: Partial<PosPurchaseReceptionPayload>,
): PosPurchaseReceptionPayload {
  return {
    operationType: 'PURCHASE_RECEPTION_CONFIRMATION',
    receptionId: 'c3d4e5f6-a7b8-9012-cdef-123456789012',
    sequentialNumber: 1,
    supplierId: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    purchaseOrderId: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    notes: null,
    createdById: 'user-inv-01',
    confirmedByUserId: 'user-inv-01',
    workstationId: 'ws-001',
    confirmedAt: '2026-07-16T11:00:00.000Z',
    metadata: {
      localReceptionId: 'c3d4e5f6-a7b8-9012-cdef-123456789012',
      workstationId: 'ws-001',
      confirmedAt: '2026-07-16T11:00:00.000Z',
    },
    ...overrides,
  };
}

function makeSupplierReturnPayload(
  overrides?: Partial<PosSupplierReturnPayload>,
): PosSupplierReturnPayload {
  return {
    operationType: 'SUPPLIER_RETURN_CONFIRMATION',
    returnId: 'd4e5f6a7-b8c9-0123-def4-567890abcdef',
    sequentialNumber: 1,
    supplierId: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    purchaseReceptionId: 'c3d4e5f6-a7b8-9012-cdef-123456789012',
    reason: 'Producto vencido',
    createdByUserId: 'user-inv-01',
    workstationId: 'ws-001',
    confirmedAt: '2026-07-16T12:00:00.000Z',
    metadata: {
      localReturnId: 'd4e5f6a7-b8c9-0123-def4-567890abcdef',
      workstationId: 'ws-001',
      confirmedAt: '2026-07-16T12:00:00.000Z',
    },
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Shared envelope assertion
// ---------------------------------------------------------------------------

function assertEnvelope(value: unknown): void {
  const obj = value as Record<string, unknown>;
  const validTypes = [
    'PURCHASE_ORDER_CONFIRMATION',
    'PURCHASE_RECEPTION_CONFIRMATION',
    'SUPPLIER_RETURN_CONFIRMATION',
  ];
  expect(validTypes).toContain(obj.operationType);
  expect(obj.operationUuid).toMatch(UUID_RE);
  expect(typeof obj.payload).toBe('object');
  expect(typeof obj.payloadHash).toBe('string');
  expect((obj.payloadHash as string).length).toBeGreaterThanOrEqual(1);
  expect(obj.sourceCreatedAt).toMatch(ISO_DATETIME_RE);
  expect(typeof obj.clientSequence).toBe('number');
  expect(Number.isInteger(obj.clientSequence)).toBe(true);
  expect((obj.clientSequence as number) > 0).toBe(true);
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('SyncQueue PURCHASE_ORDER_CONFIRMATION payload contract', () => {
  it('includes all required top-level keys', () => {
    const payload = makePurchaseOrderPayload();
    const keys = Object.keys(payload);
    expect(keys).toContain('operationType');
    expect(keys).toContain('orderId');
    expect(keys).toContain('sequentialNumber');
    expect(keys).toContain('supplierId');
    expect(keys).toContain('confirmedByUserId');
    expect(keys).toContain('workstationId');
    expect(keys).toContain('confirmedAt');
    expect(keys).toContain('metadata');
  });

  it('has valid UUIDs for entity references', () => {
    const payload = makePurchaseOrderPayload();
    expect(payload.orderId).toMatch(UUID_RE);
    expect(payload.supplierId).toMatch(UUID_RE);
  });

  it('has sequential number as positive integer', () => {
    const payload = makePurchaseOrderPayload();
    expect(payload.sequentialNumber).toBeGreaterThanOrEqual(1);
    expect(Number.isInteger(payload.sequentialNumber)).toBe(true);
  });

  it('has confirmedAt in ISO-8601 format', () => {
    const payload = makePurchaseOrderPayload();
    expect(payload.confirmedAt).toMatch(ISO_DATETIME_RE);
  });

  it('conforms to SyncOperationSchema envelope', () => {
    const envelope = {
      operationType: 'PURCHASE_ORDER_CONFIRMATION',
      operationUuid: 'e5f6a7b8-c9d0-1234-ef56-7890abcdef12',
      payload: makePurchaseOrderPayload() as unknown as Record<string, unknown>,
      payloadHash:
        'abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789',
      sourceCreatedAt: '2026-07-16T10:00:00.000Z',
      clientSequence: 5,
    };
    expect(() => assertEnvelope(envelope)).not.toThrow();
  });
});

describe('SyncQueue PURCHASE_RECEPTION_CONFIRMATION payload contract', () => {
  it('includes all required top-level keys', () => {
    const payload = makePurchaseReceptionPayload();
    const keys = Object.keys(payload);
    expect(keys).toContain('operationType');
    expect(keys).toContain('receptionId');
    expect(keys).toContain('sequentialNumber');
    expect(keys).toContain('supplierId');
    expect(keys).toContain('createdById');
    expect(keys).toContain('workstationId');
    expect(keys).toContain('confirmedAt');
    expect(keys).toContain('metadata');
  });

  it('has valid UUIDs for entity references', () => {
    const payload = makePurchaseReceptionPayload();
    expect(payload.receptionId).toMatch(UUID_RE);
    expect(payload.supplierId).toMatch(UUID_RE);
  });

  it('allows null purchaseOrderId for direct receptions without PO', () => {
    const payload = makePurchaseReceptionPayload({ purchaseOrderId: null });
    expect(payload.purchaseOrderId).toBeNull();
  });

  it('has confirmedAt in ISO-8601 format', () => {
    const payload = makePurchaseReceptionPayload();
    expect(payload.confirmedAt).toMatch(ISO_DATETIME_RE);
  });

  it('conforms to SyncOperationSchema envelope', () => {
    const envelope = {
      operationType: 'PURCHASE_RECEPTION_CONFIRMATION',
      operationUuid: 'f6a7b8c9-d0e1-2345-ef67-8901abcdef23',
      payload: makePurchaseReceptionPayload() as unknown as Record<string, unknown>,
      payloadHash:
        '1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef',
      sourceCreatedAt: '2026-07-16T11:00:00.000Z',
      clientSequence: 6,
    };
    expect(() => assertEnvelope(envelope)).not.toThrow();
  });
});

describe('SyncQueue SUPPLIER_RETURN_CONFIRMATION payload contract', () => {
  it('includes all required top-level keys', () => {
    const payload = makeSupplierReturnPayload();
    const keys = Object.keys(payload);
    expect(keys).toContain('operationType');
    expect(keys).toContain('returnId');
    expect(keys).toContain('sequentialNumber');
    expect(keys).toContain('supplierId');
    expect(keys).toContain('createdByUserId');
    expect(keys).toContain('workstationId');
    expect(keys).toContain('confirmedAt');
    expect(keys).toContain('metadata');
  });

  it('has valid UUIDs for entity references', () => {
    const payload = makeSupplierReturnPayload();
    expect(payload.returnId).toMatch(UUID_RE);
    expect(payload.supplierId).toMatch(UUID_RE);
  });

  it('allows null purchaseReceptionId for returns without original reception', () => {
    const payload = makeSupplierReturnPayload({ purchaseReceptionId: null });
    expect(payload.purchaseReceptionId).toBeNull();
  });

  it('allows null reason', () => {
    const payload = makeSupplierReturnPayload({ reason: null });
    expect(payload.reason).toBeNull();
  });

  it('has confirmedAt in ISO-8601 format', () => {
    const payload = makeSupplierReturnPayload();
    expect(payload.confirmedAt).toMatch(ISO_DATETIME_RE);
  });

  it('conforms to SyncOperationSchema envelope', () => {
    const envelope = {
      operationType: 'SUPPLIER_RETURN_CONFIRMATION',
      operationUuid: 'a7b8c9d0-e1f2-3456-7890-abcdef123456',
      payload: makeSupplierReturnPayload() as unknown as Record<string, unknown>,
      payloadHash:
        'abcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcd',
      sourceCreatedAt: '2026-07-16T12:00:00.000Z',
      clientSequence: 7,
    };
    expect(() => assertEnvelope(envelope)).not.toThrow();
  });
});
