/**
 * Sync payload contract tests — POS ↔ Server.
 *
 * These tests validate that the SyncQueue payloads generated by SalesPosService
 * conform to the shapes the server-side SyncOperationDispatcher expects when
 * replaying SALE_CONFIRMATION operations.
 *
 * ## Why a contract test
 *
 * The POS and server live in the same monorepo but are tested independently,
 * each mocking the other side.  This means a payload-shape drift between the
 * two is not caught by either test suite.  This file is the bridge: it
 * documents the server's expected payload structure and verifies the POS
 * produces it.  No Zod dependency — uses plain Vitest matchers.
 *
 * ## Server-side reference
 *
 * Server code (not imported from here, but used as the contract source of truth):
 *   apps/server/src/modules/sync/sync-operation-dispatcher.service.ts
 *     handleSaleConfirmation() reads  payload.createSaleDto, payload.confirmSaleDto,
 *     payload.userId
 *   apps/server/src/modules/sales-pos/dto/create-sale.dto.ts → CreateSaleDto
 *   apps/server/src/modules/sales-pos/dto/confirm-sale.dto.ts → ConfirmSaleDto
 *   packages/shared-validation/src/create-sale-schema.ts      → CreateSaleSchema
 *
 * @note If you change the POS's createSyncQueueEntry payload shape, update the
 *       expected shapes below AND verify against the server's dispatcher.
 */
import { describe, expect, it } from "vitest";

// ---------------------------------------------------------------------------
// Validation helpers (no Zod — just plain TypeScript + Vitest matchers)
// ---------------------------------------------------------------------------

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const SALE_TYPE_RE = /^(FREE_SALE|PRESCRIPTION|CONTROLLED_SUBSTANCE)$/;
const DECIMAL_RE = /^\d+(\.\d{1,2})?$/;
const ISO_DATETIME_RE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$/;

function assertValidCreateSaleDto(value: unknown): void {
  const obj = value as Record<string, unknown>;
  expect(obj.saleType).toMatch(SALE_TYPE_RE);
  expect(obj.cashShiftId).toMatch(UUID_RE);
  expect(
    obj.clientId === null ||
      obj.clientId === undefined ||
      (typeof obj.clientId === "string" && UUID_RE.test(obj.clientId as string)),
  ).toBe(true);
  expect(Array.isArray(obj.items)).toBe(true);
  for (const item of obj.items as Array<Record<string, unknown>>) {
    expect(item.productId).toMatch(UUID_RE);
    expect(typeof item.quantity).toBe("number");
    expect(item.unitPrice).toMatch(DECIMAL_RE);
  }
  expect(
    obj.prescriptionNumber === null ||
      obj.prescriptionNumber === undefined ||
      typeof obj.prescriptionNumber === "string",
  ).toBe(true);
}

function assertValidConfirmSaleDto(value: unknown): void {
  const obj = value as Record<string, unknown>;
  expect(Array.isArray(obj.payments)).toBe(true);
  for (const p of obj.payments as Array<Record<string, unknown>>) {
    expect(p.paymentMethodId).toMatch(UUID_RE);
    expect(typeof p.amount).toBe("number");
    expect(p.amount).toBeGreaterThan(0);
    if (p.transactionReference !== undefined && p.transactionReference !== null) {
      expect(typeof p.transactionReference).toBe("string");
    }
    if (p.cardBrand !== undefined && p.cardBrand !== null) {
      expect(typeof p.cardBrand).toBe("string");
    }
    if (p.cardLastFour !== undefined && p.cardLastFour !== null) {
      expect(typeof p.cardLastFour).toBe("string");
      expect((p.cardLastFour as string).length).toBe(4);
    }
  }
}

function assertValidSaleConfirmationPayload(value: unknown): void {
  const obj = value as Record<string, unknown>;
  expect(typeof obj.userId).toBe("string");
  expect(obj.userId).not.toBe("");
  assertValidCreateSaleDto(obj.createSaleDto);
  assertValidConfirmSaleDto(obj.confirmSaleDto);
}

function assertEnvelope(value: unknown): void {
  const obj = value as Record<string, unknown>;
  const validTypes = [
    "SALE_CONFIRMATION",
    "SHIFT_CLOSURE",
    "CLIENT_CREATION",
    "CLIENT_RETURN",
    "INVENTORY_ADJUSTMENT",
    "FISCAL_DOCUMENT_SYNC",
    "PRESCRIPTION_REGISTRATION",
    "RESOLUTION_ALLOCATION",
    "INVOICE_TRANSMISSION",
  ];
  expect(validTypes).toContain(obj.operationType);
  expect(obj.operationUuid).toMatch(UUID_RE);
  expect(typeof obj.payload).toBe("object");
  expect(typeof obj.payloadHash).toBe("string");
  expect((obj.payloadHash as string).length).toBeGreaterThanOrEqual(1);
  expect(obj.sourceCreatedAt).toMatch(ISO_DATETIME_RE);
  expect(typeof obj.clientSequence).toBe("number");
  expect(Number.isInteger(obj.clientSequence)).toBe(true);
  expect((obj.clientSequence as number) > 0).toBe(true);
}

// ---------------------------------------------------------------------------
// Expected POS-generated structure (from createSyncQueueEntry)
// ---------------------------------------------------------------------------

interface PosItemInput {
  productId: string;
  quantity: number;
  unitPrice: string;
  discountPercentage?: number;
  discountReason?: string | null;
}

interface PosPaymentInput {
  paymentMethodId: string;
  amount: number;
  transactionReference: string | null;
  authorizationCode: string | null;
  cardBrand: string | null;
  cardLastFour: string | null;
  batchNumber: string | null;
  processorResponseCode: string | null;
}

interface PosMetadata {
  localSaleId: string;
  localNumber: number;
  workstationId: string;
  sourceWorkstationId: string;
  startedAt: string;
  confirmedAt: string;
}

interface PosSyncPayload {
  createInput: {
    saleType: string;
    cashShiftId: string;
    clientId: string | null;
    items: PosItemInput[];
    prescriptionNumber: string | null;
  };
  confirmInput: {
    payments: PosPaymentInput[];
  };
  metadata: PosMetadata;
}

// ---------------------------------------------------------------------------
// Converter: POS payload → server-expected shape
// ---------------------------------------------------------------------------

/**
 * Transform a POS-generated payload into the server-expected shape.
 * This is what a future adapter/migration layer would need to do, and it is
 * documented here so the transformation is visible in the test suite.
 *
 * Server expects keys: createSaleDto, confirmSaleDto, userId
 * POS produces keys:   createInput, confirmInput, metadata
 */
function toServerPayload(pos: PosSyncPayload, userId: string): Record<string, unknown> {
  return {
    userId,
    createSaleDto: {
      saleType: pos.createInput.saleType,
      cashShiftId: pos.createInput.cashShiftId,
      clientId: pos.createInput.clientId ?? null,
      items: pos.createInput.items.map((item) => ({
        productId: item.productId,
        quantity: item.quantity,
        unitPrice: item.unitPrice,
        // Server expects `discount` (string), POS has discountPercentage (number)
        discount: item.discountPercentage
          ? String(item.discountPercentage)
          : undefined,
      })),
      prescriptionNumber: pos.createInput.prescriptionNumber,
    },
    confirmSaleDto: {
      payments: pos.confirmInput.payments.map((p) => ({
        paymentMethodId: p.paymentMethodId,
        amount: p.amount,
        transactionReference: p.transactionReference ?? undefined,
        authorizationCode: p.authorizationCode ?? undefined,
        cardBrand: p.cardBrand ?? undefined,
        cardLastFour: p.cardLastFour ?? undefined,
        batchNumber: p.batchNumber ?? undefined,
        processorResponseCode: p.processorResponseCode ?? undefined,
      })),
    },
  };
}

// ---------------------------------------------------------------------------
// Factory for a realistic POS-generated payload
// ---------------------------------------------------------------------------

function makePosSyncPayload(overrides?: Partial<PosSyncPayload>): PosSyncPayload {
  return {
    createInput: {
      saleType: "FREE_SALE",
      cashShiftId: "b1f3c2a4-5d6e-7f89-0a1b-2c3d4e5f6a7b",
      clientId: null,
      items: [
        {
          productId: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
          quantity: 2,
          unitPrice: "5000.00",
          discountPercentage: 0,
          discountReason: null,
        },
      ],
      prescriptionNumber: null,
    },
    confirmInput: {
      payments: [
        {
          paymentMethodId: "c4a5b6c7-d8e9-0123-f456-789abcdef012",
          amount: 11900,
          transactionReference: null,
          authorizationCode: null,
          cardBrand: null,
          cardLastFour: null,
          batchNumber: null,
          processorResponseCode: null,
        },
      ],
    },
    metadata: {
      localSaleId: "d7e8f9a0-b1c2-3456-7890-abcdef123456",
      localNumber: 1,
      workstationId: "ws-001",
      sourceWorkstationId: "ws-001",
      startedAt: "2026-07-16T10:00:00.000Z",
      confirmedAt: "2026-07-16T10:01:00.000Z",
    },
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("SyncQueue SALE_CONFIRMATION payload contract", () => {
  // -------------------------------------------------------------------
  // Gap documentation
  // -------------------------------------------------------------------

  describe("POS → Server key-name gap (documented)", () => {
    it("exposes the property-name mismatch between POS and server", () => {
      // This test documents the Gap — both sides must agree on property
      // names for the sync replay to work.
      const pos = makePosSyncPayload();
      const posKeys = Object.keys(pos);

      // POS sends "createInput", "confirmInput", "metadata"
      expect(posKeys).toContain("createInput");
      expect(posKeys).toContain("confirmInput");
      expect(posKeys).toContain("metadata");

      // Server expects "createSaleDto", "confirmSaleDto", "userId"
      // The POS currently does NOT include any of these.
      // TODO: Fix when either side aligns the key names.
      expect(posKeys).not.toContain("createSaleDto");
      expect(posKeys).not.toContain("confirmSaleDto");
      expect(posKeys).not.toContain("userId");
    });

    it("can be transformed to match the server-expected shape", () => {
      const pos = makePosSyncPayload();
      const serverPayload = toServerPayload(pos, "user-001");

      expect(() => assertValidSaleConfirmationPayload(serverPayload)).not.toThrow();
    });
  });

  // -------------------------------------------------------------------
  // createInput structure
  // -------------------------------------------------------------------

  describe("createInput → createSaleDto mapping", () => {
    it("matches CreateSaleDto schema after field renaming", () => {
      const pos = makePosSyncPayload();
      const serverPayload = toServerPayload(pos, "user-001");

      expect(() =>
        assertValidCreateSaleDto(serverPayload.createSaleDto),
      ).not.toThrow();
    });

    it("includes discount fields the server maps differently", () => {
      const pos = makePosSyncPayload({
        createInput: {
          ...makePosSyncPayload().createInput,
          items: [
            {
              productId: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
              quantity: 1,
              unitPrice: "5000.00",
              discountPercentage: 10,
              discountReason: "Promoción del día",
            },
          ],
        },
      });

      // POS shape has discountPercentage + discountReason
      expect(pos.createInput.items[0]?.discountPercentage).toBe(10);
      expect(pos.createInput.items[0]?.discountReason).toBe("Promoción del día");

      // After transform to server shape, discount becomes a string
      const serverPayload = toServerPayload(pos, "user-001");
      const createSaleDto = serverPayload.createSaleDto as Record<string, unknown>;
      const items = createSaleDto.items as Array<Record<string, unknown>>;

      expect(items[0]?.discount).toBe("10");
      // Server does not have discountReason at item level
    });
  });

  // -------------------------------------------------------------------
  // confirmInput structure
  // -------------------------------------------------------------------

  describe("confirmInput → confirmSaleDto mapping", () => {
    it("matches ConfirmSaleDto schema after field renaming", () => {
      const pos = makePosSyncPayload();
      const serverPayload = toServerPayload(pos, "user-001");

      expect(() =>
        assertValidConfirmSaleDto(serverPayload.confirmSaleDto),
      ).not.toThrow();
    });

    it("preserves optional payment fields when present", () => {
      const pos = makePosSyncPayload({
        confirmInput: {
          payments: [
            {
              paymentMethodId: "c4a5b6c7-d8e9-0123-f456-789abcdef012",
              amount: 50000,
              transactionReference: "TXN-001",
              authorizationCode: "AUTH-ABC",
              cardBrand: "VISA",
              cardLastFour: "1234",
              batchNumber: "BATCH-001",
              processorResponseCode: "00",
            },
          ],
        },
      });

      expect(pos.confirmInput.payments[0]?.transactionReference).toBe("TXN-001");
      expect(pos.confirmInput.payments[0]?.cardBrand).toBe("VISA");
      expect(pos.confirmInput.payments[0]?.cardLastFour).toBe("1234");
    });
  });

  // -------------------------------------------------------------------
  // Metadata — local audit data
  // -------------------------------------------------------------------

  describe("metadata — local audit data", () => {
    it("includes localSaleId for correlating server replay results", () => {
      const pos = makePosSyncPayload();
      expect(pos.metadata.localSaleId).toMatch(UUID_RE);
    });

    it("includes timestamps in ISO-8601 format", () => {
      const pos = makePosSyncPayload();
      expect(pos.metadata.startedAt).toMatch(ISO_DATETIME_RE);
      expect(pos.metadata.confirmedAt).toMatch(ISO_DATETIME_RE);
    });

    it("includes workstation identifiers", () => {
      const pos = makePosSyncPayload();
      expect(pos.metadata.workstationId).toBe("ws-001");
      expect(pos.metadata.sourceWorkstationId).toBe(pos.metadata.workstationId);
    });

    it("includes the sequential local number", () => {
      const pos = makePosSyncPayload();
      expect(pos.metadata.localNumber).toBeGreaterThanOrEqual(1);
    });
  });

  // -------------------------------------------------------------------
  // SyncOperationSchema envelope (shared contract)
  // -------------------------------------------------------------------

  describe("SyncOperationSchema envelope", () => {
    /**
     * The outer envelope is validated server-side by SyncOperationSchema
     * (apps/server/src/modules/sync/dto/sync-operation.schema.ts).
     * Even though the payload key names inside differ, the envelope fields
     * (operationType, operationUuid, payload, payloadHash, sourceCreatedAt,
     * clientSequence) are checked by Zod before the dispatcher sees the
     * payload.  These tests document the envelope fields the POS must
     * provide, mirrored inline here.
     */
    it("conforms to the server's envelope format", () => {
      const envelope = {
        operationType: "SALE_CONFIRMATION",
        operationUuid: "b0a1b2c3-d4e5-6789-0abc-def123456789",
        payload: makePosSyncPayload() as unknown as Record<string, unknown>,
        payloadHash:
          "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
        sourceCreatedAt: "2026-07-16T10:01:00.000Z",
        clientSequence: 42,
      };

      expect(() => assertEnvelope(envelope)).not.toThrow();
    });

    it("rejects an invalid operation type", () => {
      expect(() =>
        assertEnvelope({
          operationType: "INVALID_TYPE",
          operationUuid: "b0a1b2c3-d4e5-6789-0abc-def123456789",
          payload: {},
          payloadHash: "abc",
          sourceCreatedAt: "2026-07-16T10:01:00.000Z",
          clientSequence: 1,
        }),
      ).toThrow();
    });

    it("rejects a non-UUID operationUuid", () => {
      expect(() =>
        assertEnvelope({
          operationType: "SALE_CONFIRMATION",
          operationUuid: "not-a-uuid",
          payload: {},
          payloadHash: "abc",
          sourceCreatedAt: "2026-07-16T10:01:00.000Z",
          clientSequence: 1,
        }),
      ).toThrow();
    });

    it("rejects a non-positive clientSequence", () => {
      expect(() =>
        assertEnvelope({
          operationType: "SALE_CONFIRMATION",
          operationUuid: "b0a1b2c3-d4e5-6789-0abc-def123456789",
          payload: {},
          payloadHash: "abc",
          sourceCreatedAt: "2026-07-16T10:01:00.000Z",
          clientSequence: 0,
        }),
      ).toThrow();
    });
  });
});

// ---------------------------------------------------------------------------
// Integration note
// ---------------------------------------------------------------------------
// The payloadHash follows SHA-256 (64 hex chars).  The server's
// ingestOperation recomputes the hash from the parsed payload and compares it
// to the submitted payloadHash.  If the POS changes the payload structure
// (e.g. renames a field), the hash changes and the server rejects the batch
// with PAYLOAD_HASH_MISMATCH.  Keep the hash computation in
// SalesPosService.computePayloadHash() in sync with the actual serialised
// payload.
//
// Current known gap (as of Jul 2026):
//   POS sends:   { createInput, confirmInput, metadata }
//   Server expects: { createSaleDto, confirmSaleDto, userId }
//   Fix needed in either:
//     a) POS's createSyncQueueEntry to emit the server-expected keys, OR
//     b) Server's handleSaleConfirmation to read the POS keys
//   The transformation in toServerPayload() shows what the mapping looks
//   like once a decision is made.
