/**
 * Sync payload contract tests — POS ClientReturn ↔ Server.
 *
 * These tests validate that the SyncQueue payloads generated by
 * ReturnsService.confirm() conform to the shape the server-side
 * SyncOperationDispatcher expects when replaying CLIENT_RETURN operations.
 *
 * ## Server-side reference
 *
 * Server code (not imported from here, but used as the contract source of truth):
 *   apps/server/src/modules/sync/sync-operation-dispatcher.service.ts
 *     handleClientReturn() reads payload.createdById, payload.workstationId,
 *     payload.metadata.localReturnId, payload.saleId, payload.refundMethodId,
 *     payload.reason, payload.items[].saleItemId, payload.items[].quantity,
 *     payload.items[].lots[].lotId, payload.items[].lots[].quantity
 *   apps/server/src/modules/returns/dto/create-client-return.dto.ts
 *     → CreateClientReturnDto (Zod schema)
 *
 * @note If you change the POS's createSyncQueueEntry payload shape, update the
 *       expected shapes below AND verify against the server's dispatcher.
 */
import { describe, expect, it } from "vitest";

// ---------------------------------------------------------------------------
// Validation helpers
// ---------------------------------------------------------------------------

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const DECIMAL_RE = /^\d+(\.\d{1,2})?$/;
const ISO_DATETIME_RE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$/;

function assertValidReturnItem(value: unknown): void {
  const obj = value as Record<string, unknown>;

  expect(obj.saleItemId).toMatch(UUID_RE);
  expect(typeof obj.quantity).toBe("number");
  expect(Number.isInteger(obj.quantity)).toBe(true);
  expect(obj.quantity).toBeGreaterThan(0);

  expect(obj.unitPriceAtSale).toMatch(DECIMAL_RE);
  expect(obj.unitPriceAtReturn).toMatch(DECIMAL_RE);
  expect(obj.taxAmount).toMatch(DECIMAL_RE);
  expect(obj.totalAmount).toMatch(DECIMAL_RE);

  // Lots array
  expect(Array.isArray(obj.lots)).toBe(true);
  expect((obj.lots as Array<unknown>).length).toBeGreaterThan(0);
  for (const lot of obj.lots as Array<Record<string, unknown>>) {
    expect(lot.lotId).toMatch(UUID_RE);
    expect(typeof lot.quantity).toBe("number");
    expect(Number.isInteger(lot.quantity)).toBe(true);
    expect(lot.quantity).toBeGreaterThan(0);
  }
}

function assertValidClientReturnPayload(value: unknown): void {
  const obj = value as Record<string, unknown>;

  // Top-level identifiers the server reads directly
  expect(obj.saleId).toMatch(UUID_RE);
  expect(typeof obj.createdById).toBe("string");
  expect((obj.createdById as string).length).toBeGreaterThan(0);
  expect(obj.refundMethodId).toMatch(UUID_RE);

  // Optional fields
  if (obj.reason !== null && obj.reason !== undefined) {
    expect(typeof obj.reason).toBe("string");
  }
  if (obj.notes !== null && obj.notes !== undefined) {
    expect(typeof obj.notes).toBe("string");
  }

  // Financial amounts as Decimal strings
  expect(obj.refundAmount).toMatch(DECIMAL_RE);
  expect(obj.subtotalReturned).toMatch(DECIMAL_RE);
  expect(obj.taxReturned).toMatch(DECIMAL_RE);

  // Items array
  expect(Array.isArray(obj.items)).toBe(true);
  expect((obj.items as Array<unknown>).length).toBeGreaterThan(0);
  for (const item of obj.items as Array<unknown>) {
    assertValidReturnItem(item);
  }

  // Metadata for server correlation
  const metadata = obj.metadata as Record<string, unknown> | undefined;
  expect(metadata).toBeDefined();
  expect(metadata?.localReturnId).toMatch(UUID_RE);
  expect(typeof metadata?.workstationId).toBe("string");
  expect((metadata?.workstationId as string).length).toBeGreaterThan(0);
  expect(metadata?.confirmedAt).toMatch(ISO_DATETIME_RE);
}

function assertEnvelope(value: unknown): void {
  const obj = value as Record<string, unknown>;
  const validTypes = [
    "SALE_CONFIRMATION",
    "SHIFT_CLOSURE",
    "CLIENT_CREATION",
    "CLIENT_RETURN",
    "INVENTORY_ADJUSTMENT",
    "FISCAL_DOCUMENT_SYNC",
    "PRESCRIPTION_REGISTRATION",
    "RESOLUTION_ALLOCATION",
    "INVOICE_TRANSMISSION",
  ];
  expect(validTypes).toContain(obj.operationType);
  expect(obj.operationUuid).toMatch(UUID_RE);
  expect(typeof obj.payload).toBe("object");
  expect(typeof obj.payloadHash).toBe("string");
  expect((obj.payloadHash as string).length).toBeGreaterThanOrEqual(1);
  expect(obj.sourceCreatedAt).toMatch(ISO_DATETIME_RE);
  expect(typeof obj.clientSequence).toBe("number");
  expect(Number.isInteger(obj.clientSequence)).toBe(true);
  expect((obj.clientSequence as number) > 0).toBe(true);
}

// ---------------------------------------------------------------------------
// Expected POS-generated structure (from createSyncQueueEntry)
// ---------------------------------------------------------------------------

interface PosReturnLot {
  lotId: string;
  quantity: number;
}

interface PosReturnItem {
  saleItemId: string;
  quantity: number;
  unitPriceAtSale: string;
  unitPriceAtReturn: string;
  taxAmount: string;
  totalAmount: string;
  lots: PosReturnLot[];
}

interface PosReturnMetadata {
  localReturnId: string;
  workstationId: string;
  confirmedAt: string;
}

interface PosClientReturnPayload {
  returnId: string;
  sequentialNumber: number;
  saleId: string;
  clientId: string;
  refundAmount: string;
  subtotalReturned: string;
  taxReturned: string;
  refundMethodId: string;
  reason: string | null;
  notes: string | null;
  createdById: string;
  cashShiftId: string;
  workstationId: string;
  items: PosReturnItem[];
  metadata: PosReturnMetadata;
}

// ---------------------------------------------------------------------------
// Factory for a realistic POS-generated payload
// ---------------------------------------------------------------------------

function makePosPayload(
  overrides?: Partial<PosClientReturnPayload>,
): PosClientReturnPayload {
  return {
    returnId: "d7e8f9a0-b1c2-3456-7890-abcdef123456",
    sequentialNumber: 1,
    saleId: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    clientId: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
    refundAmount: "50000.00",
    subtotalReturned: "42016.81",
    taxReturned: "7983.19",
    refundMethodId: "c4a5b6c7-d8e9-0123-f456-789abcdef012",
    reason: "Cliente devolvió producto por error en la compra",
    notes: null,
    createdById: "user-cashier-01",
    cashShiftId: "f1a2b3c4-d5e6-7890-abcd-ef1234567890",
    workstationId: "ws-001",
    items: [
      {
        saleItemId: "e5f6a7b8-c9d0-1234-ef56-789abcdef012",
        quantity: 2,
        unitPriceAtSale: "25000.00",
        unitPriceAtReturn: "25000.00",
        taxAmount: "3991.60",
        totalAmount: "50000.00",
        lots: [
          {
            lotId: "c3d4e5f6-a7b8-9012-cdef-123456789012",
            quantity: 2,
          },
        ],
      },
    ],
    metadata: {
      localReturnId: "d7e8f9a0-b1c2-3456-7890-abcdef123456",
      workstationId: "ws-001",
      confirmedAt: "2026-07-16T10:01:00.000Z",
    },
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("SyncQueue CLIENT_RETURN payload contract", () => {
  describe("POS payload matches server-expected shape directly", () => {
    it("includes all server-expected keys at the top level", () => {
      const payload = makePosPayload();
      const keys = Object.keys(payload);

      // Core fields the server dispatcher reads
      expect(keys).toContain("saleId");
      expect(keys).toContain("createdById");
      expect(keys).toContain("refundMethodId");
      expect(keys).toContain("items");
      expect(keys).toContain("metadata");
    });

    it("passes server-side validation without transformation", () => {
      const payload = makePosPayload();

      expect(() =>
        assertValidClientReturnPayload(payload),
      ).not.toThrow();
    });
  });

  describe("items structure", () => {
    it("matches CreateClientReturnDto items schema", () => {
      const payload = makePosPayload();

      for (const item of payload.items) {
        expect(() => assertValidReturnItem(item)).not.toThrow();
      }
    });

    it("supports multiple items across different lots", () => {
      const payload = makePosPayload({
        items: [
          {
            saleItemId: "e5f6a7b8-c9d0-1234-ef56-789abcdef012",
            quantity: 1,
            unitPriceAtSale: "25000.00",
            unitPriceAtReturn: "25000.00",
            taxAmount: "1995.80",
            totalAmount: "25000.00",
            lots: [{ lotId: "c3d4e5f6-a7b8-9012-cdef-123456789012", quantity: 1 }],
          },
          {
            saleItemId: "f6a7b8c9-d0e1-2345-f678-90abcdef0123",
            quantity: 3,
            unitPriceAtSale: "15000.00",
            unitPriceAtReturn: "15000.00",
            taxAmount: "3592.44",
            totalAmount: "45000.00",
            lots: [
              { lotId: "d4e5f6a7-b8c9-0123-def4-567890abcdef", quantity: 2 },
              { lotId: "e5f6a7b8-c9d0-1234-ef56-789abcdef012", quantity: 1 },
            ],
          },
        ],
      });

      expect(payload.items).toHaveLength(2);
      expect(payload.items[1]?.lots).toHaveLength(2);
    });
  });

  describe("financial amounts", () => {
    it("are serialised as Decimal-compatible strings", () => {
      const payload = makePosPayload();

      expect(payload.refundAmount).toMatch(DECIMAL_RE);
      expect(payload.subtotalReturned).toMatch(DECIMAL_RE);
      expect(payload.taxReturned).toMatch(DECIMAL_RE);

      for (const item of payload.items) {
        expect(item.unitPriceAtSale).toMatch(DECIMAL_RE);
        expect(item.unitPriceAtReturn).toMatch(DECIMAL_RE);
        expect(item.taxAmount).toMatch(DECIMAL_RE);
        expect(item.totalAmount).toMatch(DECIMAL_RE);
      }
    });
  });

  describe("createdById — operator identity", () => {
    it("is a non-empty string the server uses as userId", () => {
      const payload = makePosPayload();
      expect(typeof payload.createdById).toBe("string");
      expect(payload.createdById.length).toBeGreaterThan(0);
    });
  });

  describe("metadata — local audit data", () => {
    it("includes localReturnId for correlating server-side credit notes", () => {
      const payload = makePosPayload();
      expect(payload.metadata.localReturnId).toMatch(UUID_RE);
      expect(payload.metadata.localReturnId).toBe(payload.returnId);
    });

    it("includes workstation identifier", () => {
      const payload = makePosPayload();
      expect(payload.metadata.workstationId).toBe("ws-001");
    });

    it("includes confirmedAt in ISO-8601 format", () => {
      const payload = makePosPayload();
      expect(payload.metadata.confirmedAt).toMatch(ISO_DATETIME_RE);
    });
  });

  describe("SyncOperationSchema envelope", () => {
    it("conforms to the server's envelope format", () => {
      const envelope = {
        operationType: "CLIENT_RETURN",
        operationUuid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        payload: makePosPayload() as unknown as Record<string, unknown>,
        payloadHash:
          "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
        sourceCreatedAt: "2026-07-16T10:01:00.000Z",
        clientSequence: 15,
      };

      expect(() => assertEnvelope(envelope)).not.toThrow();
    });

    it("rejects an invalid operation type", () => {
      expect(() =>
        assertEnvelope({
          operationType: "INVALID_TYPE",
          operationUuid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
          payload: {},
          payloadHash: "abc",
          sourceCreatedAt: "2026-07-16T10:01:00.000Z",
          clientSequence: 1,
        }),
      ).toThrow();
    });
  });
});
