import { z } from 'zod';

/**
 * Local schema for a single sync operation in a batch payload.
 * Matches the SyncQueue model: operationType uses the Prisma SyncOperationType
 * values; operationUuid is the idempotency key generated by the offline device.
 * sourceWorkstationId is injected from the authenticated session, not the body.
 */
/**
 * Matches the Prisma SyncOperationType enum in shared/_shared-enums.prisma.
 * Kept as a strict enum so Zod rejects unknown types before they reach Prisma.
 */
/**
 * Source of a sync operation:
 * - DIRECT: pushed directly from the originating workstation
 * - LOCAL_HUB: relayed through a hub workstation on the local network
 */
export const SyncSourceSchema = z.enum(['DIRECT', 'LOCAL_HUB']);
export type SyncSource = z.infer<typeof SyncSourceSchema>;

export const SyncOperationSchema = z.object({
  operationType: z.enum([
    'SALE_CONFIRMATION',
    'SHIFT_CLOSURE',
    'CLIENT_CREATION',
    'CLIENT_UPDATE',
    'CLIENT_DEACTIVATE',
    'CLIENT_RETURN',
    'INVENTORY_ADJUSTMENT',
    'FISCAL_DOCUMENT_SYNC',
    'PRESCRIPTION_REGISTRATION',
    'RESOLUTION_ALLOCATION',
    'INVOICE_TRANSMISSION',
    'INVOICE_TRANSMISSION_RESULT',
    'PRODUCT_CREATION',
    'PRODUCT_UPDATE',
  ]),
  operationUuid: z.string().uuid('Invalid operation UUID'),
  payload: z.record(z.string(), z.any()),
  payloadHash: z.string().min(1, 'Payload hash is required'),
  sourceCreatedAt: z.string().datetime('Invalid ISO 8601 datetime'),
  clientSequence: z
    .number()
    .int()
    .positive('Client sequence must be a positive integer'),
  /** Origin of the operation. Defaults to DIRECT for backward compatibility. */
  source: SyncSourceSchema.optional().default('DIRECT'),
});

export type SyncOperationInput = z.infer<typeof SyncOperationSchema>;

/**
 * The POS desktop POSTs a JSON array of operations directly (no wrapper).
 * Schema matches the client's wire format.
 */
export const SyncBatchSchema = z
  .array(SyncOperationSchema)
  .min(1, 'At least one operation is required');

export type SyncBatchInput = z.infer<typeof SyncBatchSchema>;
