import { z } from 'zod';

/**
 * Local schema for a single sync operation in a batch payload.
 * Matches the SyncQueue model: operationType uses the Prisma SyncOperationType
 * values; operationUuid is the idempotency key generated by the offline device.
 * sourceWorkstationId is injected from the authenticated session, not the body.
 */
export const SyncOperationSchema = z.object({
  operationType: z.enum([
    'SALE_CONFIRMATION',
    'SHIFT_CLOSURE',
    'CLIENT_CREATION',
    'CLIENT_RETURN',
    'INVENTORY_ADJUSTMENT',
    'FISCAL_DOCUMENT_SYNC',
    'PRESCRIPTION_REGISTRATION',
    'RESOLUTION_ALLOCATION',
    'INVOICE_TRANSMISSION',
  ]),
  operationUuid: z.string().uuid('Invalid operation UUID'),
  payload: z.record(z.string(), z.any()),
  payloadHash: z.string().min(1, 'Payload hash is required'),
  sourceCreatedAt: z.string().datetime('Invalid ISO 8601 datetime'),
  clientSequence: z
    .number()
    .int()
    .positive('Client sequence must be a positive integer'),
});

export type SyncOperationInput = z.infer<typeof SyncOperationSchema>;

export const SyncBatchSchema = z.object({
  operations: z
    .array(SyncOperationSchema)
    .min(1, 'At least one operation is required'),
});

export type SyncBatchInput = z.infer<typeof SyncBatchSchema>;
