import { Injectable } from '@nestjs/common';
import { Prisma } from '@pharmacy/database';
import { CashCountType } from '@pharmacy/shared-types';
import { CashShiftService } from '@/modules/cash-shift/cash-shift.service';
import { ClientsService } from '@/modules/clients/clients.service';
import { SalesService } from '@/modules/sales-pos/services/sales.service';
import { InventoryAdjustmentsService } from '@/modules/inventory-lots/services/inventory-adjustments.service';
import type { SyncQueueEntry } from './entities/sync-queue-entry.entity';
import type { CreateSaleDto } from '@/modules/sales-pos/dto/create-sale.dto';
import type { ConfirmSaleDto } from '@/modules/sales-pos/dto/confirm-sale.dto';
import type { CreateClientDto } from '@/modules/clients/dto/create-client.dto';
import type { CreateInventoryAdjustmentDto } from '@/modules/inventory-lots/dto/create-inventory-adjustment.dto';

/**
 * Re-executes the real business logic for each supported offline operation.
 * This is NOT a blind trust of the offline payload — it re-validates every
 * constraint against the server's current state.
 */
@Injectable()
export class SyncOperationDispatcherService {
  constructor(
    private readonly cashShiftService: CashShiftService,
    private readonly clientsService: ClientsService,
    private readonly salesService: SalesService,
    private readonly inventoryAdjustmentsService: InventoryAdjustmentsService,
  ) {}

  /** Routes a SyncQueue entry to the appropriate replay handler. */
  async dispatch(entry: SyncQueueEntry): Promise<void> {
    switch (entry.operationType) {
      case 'SALE_CONFIRMATION':
        await this.handleSaleConfirmation(entry);
        break;
      case 'SHIFT_CLOSURE':
        await this.handleShiftClosure(entry);
        break;
      case 'CLIENT_CREATION':
        await this.handleClientCreation(entry);
        break;
      case 'INVENTORY_ADJUSTMENT':
        await this.handleInventoryAdjustment(entry);
        break;
      // FISCAL_DOCUMENT_SYNC, PRESCRIPTION_REGISTRATION, RESOLUTION_ALLOCATION
      // are not dispatched — the job never selects them.
    }
  }

  /** Replays a SALE_CONFIRMATION by creating and confirming the sale server-side. */
  private async handleSaleConfirmation(entry: SyncQueueEntry): Promise<void> {
    const payload = JSON.parse(entry.payload) as Record<string, unknown>;
    const userId = payload.userId as string;
    const workstationId = entry.sourceWorkstationId;

    const sale = await this.salesService.create(
      payload.createSaleDto as unknown as CreateSaleDto,
      userId,
      workstationId,
    );
    await this.salesService.confirm(
      (sale as { id: string }).id,
      payload.confirmSaleDto as unknown as ConfirmSaleDto,
      userId,
    );
  }

  /** Replays a SHIFT_CLOSURE: registers closing cash counts then closes the shift. */
  private async handleShiftClosure(entry: SyncQueueEntry): Promise<void> {
    const payload = JSON.parse(entry.payload) as Record<string, unknown>;
    const userId = payload.userId as string;
    const shiftId = payload.shiftId as string;
    const cashCounts = payload.cashCounts as Array<Record<string, unknown>> | undefined;

    for (const count of cashCounts ?? []) {
      await this.cashShiftService.registerCashCount(shiftId, userId, {
        countType: count.countType as CashCountType,
        paymentMethodId: count.paymentMethodId as string,
        expectedAmount: new Prisma.Decimal(count.expectedAmount as string),
        declaredAmount: new Prisma.Decimal(count.declaredAmount as string),
        denominationsBreakdown: count.denominationsBreakdown as
          | Record<string, number>
          | undefined,
      });
    }
    await this.cashShiftService.closeShift(shiftId, userId, {
      closingNotes: payload.closingNotes as string | undefined,
    });
  }

  /**
   * Replays a CLIENT_CREATION by creating or updating the client server-side.
   *
   * The local UUID generated by the POS is preserved via `localClientId` so
   * that future sync operations referencing this client (e.g. sale confirmations)
   * resolve correctly. If the `[identificationType, identificationNumber]`
   * unique constraint is violated, the `clientsService.create` method performs
   * an upsert — the POS's data is treated as the latest version
   * ("last writer wins" strategy).
   */
  private async handleClientCreation(entry: SyncQueueEntry): Promise<void> {
    const payload = JSON.parse(entry.payload) as Record<string, unknown>;
    const userId = payload.userId as string;
    const createClientDto = payload.createClientDto as unknown as CreateClientDto;
    const localClientId = payload.localClientId as string | undefined;

    await this.clientsService.create(
      createClientDto,
      userId,
      localClientId,
    );
  }

  /**
   * Replays an INVENTORY_ADJUSTMENT by creating the document in DRAFT.
   * The normal Phase 16 approval chain must be followed — sync does not
   * bypass that gate.
   */
  private async handleInventoryAdjustment(entry: SyncQueueEntry): Promise<void> {
    const payload = JSON.parse(entry.payload) as Record<string, unknown>;
    await this.inventoryAdjustmentsService.create(
      payload.createAdjustmentDto as unknown as CreateInventoryAdjustmentDto,
      payload.userId as string,
    );
  }
}
