//! Tauri command handlers for printer discovery, test printing, status,
//! file-based printing, temp file writing, and file existence checks.
//!
//! Each command is intentionally thin: validate input, delegate to the domain
//! module in `crate::printer_discovery`, and map errors into a serializable result.

use tauri::{command, AppHandle};

use serde::{Deserialize, Serialize};

use crate::printer_discovery::{
    self, DiscoveredPrinter, DrawerResult, PrintResult, PrinterStatusResponse, TestPrintResult,
};

/// Enumerate all printers the OS knows about.
#[command]
pub fn discover_printers() -> Result<Vec<DiscoveredPrinter>, String> {
    printer_discovery::discover_printers()
}

/// Scan a /24 subnet for network printers on common ports (9100, 631, 515).
#[command]
pub async fn scan_network_printers(subnet: String) -> Result<Vec<DiscoveredPrinter>, String> {
    printer_discovery::scan_network_printers(subnet).await
}

/// Send a test page to a specific printer.
#[command]
pub async fn test_print(
    printer_system_name: String,
    payload_type: String,
) -> Result<TestPrintResult, String> {
    printer_discovery::test_print(printer_system_name, payload_type).await
}

/// Get the current status of a specific printer (best-effort).
#[command]
pub async fn get_printer_status(
    printer_system_name: String,
) -> Result<PrinterStatusResponse, String> {
    printer_discovery::get_printer_status(printer_system_name).await
}

/// Print an existing file to a specific printer.
///
/// This is the production print path for receipts, invoices, reports, etc.
/// The file must already exist on disk at the given path.
#[command]
pub async fn print_file(
    printer_system_name: String,
    file_path: String,
) -> Result<TestPrintResult, String> {
    printer_discovery::print_file(printer_system_name, file_path).await
}

/// Write a temporary print payload file to the app data directory.
///
/// Creates the `print-queue/` subdirectory as needed, writes the content,
/// and returns the absolute file path. The returned path can be tracked in
/// the print queue and passed to `print_file` for production printing.
#[command]
pub fn write_temp_file(app: AppHandle, filename: String, content: String) -> Result<String, String> {
    printer_discovery::write_temp_file(&app, &filename, &content)
}

/// Check whether a file exists at the given path.
///
/// Used by the print queue to verify that a queued payload file still
/// exists before attempting to print it.
#[command]
pub fn file_exists(path: String) -> bool {
    printer_discovery::file_exists(&path)
}

/// Send raw ESC/POS bytes to a thermal receipt printer.
///
/// Used for thermal receipt templates generated on the TS side by the
/// escpos-formatter. The commands are raw bytes including text, formatting,
/// QR codes, barcodes, and the paper cut command.
#[command]
pub async fn print_escpos(
    printer_system_name: String,
    commands: Vec<u8>,
) -> Result<PrintResult, String> {
    printer_discovery::print_escpos(printer_system_name, commands).await
}

/// Send a label image to a label printer.
///
/// The image at `image_path` is typically an HTML file generated by the
/// label-formatter on the TS side. The file is sent to the printer via
/// the OS print subsystem.
#[command]
pub async fn print_label_image(
    printer_system_name: String,
    image_path: String,
) -> Result<PrintResult, String> {
    printer_discovery::print_label_image(printer_system_name, image_path).await
}

/// Open the cash drawer connected to a printer.
///
/// Sends the standard ESC/POS cash drawer kick command. The optional
/// `kick_command` overrides the default bytes (0x1B 0x70 0x00 0x32 0xFA).
/// This is called by the CashDrawerService on the TS side.
#[command]
pub async fn open_cash_drawer(
    printer_system_name: String,
    kick_command: Option<Vec<u8>>,
) -> Result<DrawerResult, String> {
    printer_discovery::open_cash_drawer(printer_system_name, kick_command).await
}

/// Send text to a customer display connected via a printer's pass-through.
///
/// The text has already been formatted by the CustomerDisplayService on
/// the TS side. This command writes the bytes to the printer device.
#[command]
pub async fn customer_display_update(
    printer_system_name: String,
    text: String,
    encoding: String,
) -> Result<DrawerResult, String> {
    printer_discovery::customer_display_update(printer_system_name, text, encoding).await
}

/// Detect the paper size for a given printer name and driver name.
///
/// Uses the same heuristics as `discover_printers` to suggest a paper
/// size. The result includes the detected size and a confidence level
/// so the UI can show "Detectado: 80 mm (alta confianza)" or let the
/// user override.
#[command]
pub fn detect_printer_paper_size(
    printer_name: String,
    driver_name: String,
    printer_type: String,
) -> Result<PrinterPaperSizeResult, String> {
    use crate::printer_discovery;
    let (paper_size, confidence) =
        printer_discovery::detect_paper_size(&printer_name, &driver_name, &printer_type);
    let description = printer_discovery::paper_size_description(&paper_size);
    let char_width = printer_discovery::paper_size_char_width(&paper_size);

    Ok(PrinterPaperSizeResult {
        paper_size,
        confidence,
        description: description.to_string(),
        char_width,
    })
}

/// Result from the `detect_printer_paper_size` command.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PrinterPaperSizeResult {
    /// One of the PaperSize enum values (RECEIPT_80MM, etc.).
    pub paper_size: String,
    /// "high", "medium", "low", or "none".
    pub confidence: String,
    /// Human-readable description in Spanish.
    pub description: String,
    /// Approximate character width at 12CPI for this paper size.
    pub char_width: u32,
}
