/**
 * Sync payload contract tests — POS PrescriptionRegistration ↔ Server.
 *
 * These tests validate that the SyncQueue payloads generated by
 * PrescriptionsService.create() conform to the shape the server-side
 * SyncOperationDispatcher expects when replaying PRESCRIPTION_REGISTRATION
 * operations.
 *
 * ## Server-side reference
 *
 * Server code (not imported from here, but used as the contract source of truth):
 *   apps/server/src/modules/sync/sync-operation-dispatcher.service.ts
 *     handlePrescriptionRegistration() reads payload.saleItemId,
 *     payload.prescriptionId, payload.isControlledSubstance
 *
 * @note If you change the POS's createSyncQueueEntry payload shape, update the
 *       expected shapes below AND verify against the server's dispatcher.
 */
import { describe, expect, it } from "vitest";

// ---------------------------------------------------------------------------
// Validation helpers
// ---------------------------------------------------------------------------

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const ISO_DATETIME_RE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$/;

function assertValidPrescriptionRegistrationPayload(value: unknown): void {
  const obj = value as Record<string, unknown>;

  // Server reads these directly
  expect(obj.prescriptionId).toMatch(UUID_RE);
  expect(obj.saleItemId).toMatch(UUID_RE);
  expect(typeof obj.isControlledSubstance).toBe("boolean");

  // Optional fields
  if (obj.prescriptionNumber !== null && obj.prescriptionNumber !== undefined) {
    expect(typeof obj.prescriptionNumber).toBe("string");
  }
  if (obj.prescriberIdNumber !== null && obj.prescriberIdNumber !== undefined) {
    expect(typeof obj.prescriberIdNumber).toBe("string");
  }
  if (obj.prescriberName !== null && obj.prescriberName !== undefined) {
    expect(typeof obj.prescriberName).toBe("string");
  }

  // Metadata
  const metadata = obj.metadata as Record<string, unknown> | undefined;
  expect(metadata).toBeDefined();
  expect(typeof metadata?.userId).toBe("string");
  expect((metadata?.userId as string).length).toBeGreaterThan(0);
  expect(typeof metadata?.workstationId).toBe("string");
  expect((metadata?.workstationId as string).length).toBeGreaterThan(0);
  expect(metadata?.createdAt).toMatch(ISO_DATETIME_RE);
}

function assertEnvelope(value: unknown): void {
  const obj = value as Record<string, unknown>;
  const validTypes = [
    "SALE_CONFIRMATION",
    "SHIFT_CLOSURE",
    "CLIENT_CREATION",
    "CLIENT_RETURN",
    "INVENTORY_ADJUSTMENT",
    "FISCAL_DOCUMENT_SYNC",
    "PRESCRIPTION_REGISTRATION",
    "RESOLUTION_ALLOCATION",
    "INVOICE_TRANSMISSION",
  ];
  expect(validTypes).toContain(obj.operationType);
  expect(obj.operationUuid).toMatch(UUID_RE);
  expect(typeof obj.payload).toBe("object");
  expect(typeof obj.payloadHash).toBe("string");
  expect((obj.payloadHash as string).length).toBeGreaterThanOrEqual(1);
  expect(obj.sourceCreatedAt).toMatch(ISO_DATETIME_RE);
  expect(typeof obj.clientSequence).toBe("number");
  expect(Number.isInteger(obj.clientSequence)).toBe(true);
  expect((obj.clientSequence as number) > 0).toBe(true);
}

// ---------------------------------------------------------------------------
// Expected POS-generated structure (from createSyncQueueEntry)
// ---------------------------------------------------------------------------

interface PosPrescriptionMetadata {
  userId: string;
  workstationId: string;
  createdAt: string;
}

interface PosPrescriptionRegistrationPayload {
  prescriptionId: string;
  saleItemId: string;
  prescriptionNumber: string | null;
  prescriberIdNumber: string | null;
  prescriberName: string | null;
  isControlledSubstance: boolean;
  metadata: PosPrescriptionMetadata;
}

// ---------------------------------------------------------------------------
// Factory for a realistic POS-generated payload
// ---------------------------------------------------------------------------

function makePosPayload(
  overrides?: Partial<PosPrescriptionRegistrationPayload>,
): PosPrescriptionRegistrationPayload {
  return {
    prescriptionId: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    saleItemId: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
    prescriptionNumber: "RX-2026-0042",
    prescriberIdNumber: "CC-987654321",
    prescriberName: "Dra. María Rodríguez",
    isControlledSubstance: true,
    metadata: {
      userId: "user-cashier-01",
      workstationId: "ws-001",
      createdAt: "2026-07-16T10:00:00.000Z",
    },
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("SyncQueue PRESCRIPTION_REGISTRATION payload contract", () => {
  describe("POS payload matches server-expected shape directly", () => {
    it("includes all server-expected keys at the top level", () => {
      const payload = makePosPayload();
      const keys = Object.keys(payload);

      // Fields the server dispatcher reads
      expect(keys).toContain("prescriptionId");
      expect(keys).toContain("saleItemId");
      expect(keys).toContain("isControlledSubstance");
      expect(keys).toContain("metadata");
    });

    it("passes server-side validation without transformation", () => {
      const payload = makePosPayload();

      expect(() =>
        assertValidPrescriptionRegistrationPayload(payload),
      ).not.toThrow();
    });
  });

  describe("mandatory fields", () => {
    it("prescriptionId is a valid UUID", () => {
      const payload = makePosPayload();
      expect(payload.prescriptionId).toMatch(UUID_RE);
    });

    it("saleItemId is a valid UUID", () => {
      const payload = makePosPayload();
      expect(payload.saleItemId).toMatch(UUID_RE);
    });

    it("isControlledSubstance is a boolean", () => {
      const freePayload = makePosPayload({ isControlledSubstance: false });
      expect(typeof freePayload.isControlledSubstance).toBe("boolean");
      expect(freePayload.isControlledSubstance).toBe(false);

      const controlledPayload = makePosPayload({ isControlledSubstance: true });
      expect(controlledPayload.isControlledSubstance).toBe(true);
    });
  });

  describe("optional fields", () => {
    it("can be null for non-controlled prescriptions", () => {
      const payload = makePosPayload({
        prescriptionNumber: null,
        prescriberIdNumber: null,
        prescriberName: null,
        isControlledSubstance: false,
      });

      expect(payload.prescriptionNumber).toBeNull();
      expect(payload.prescriberIdNumber).toBeNull();
      expect(payload.prescriberName).toBeNull();
      expect(() =>
        assertValidPrescriptionRegistrationPayload(payload),
      ).not.toThrow();
    });

    it("carry prescriber details when present", () => {
      const payload = makePosPayload({
        prescriptionNumber: "RX-2026-0099",
        prescriberIdNumber: "CC-123456789",
        prescriberName: "Dr. Carlos López",
      });

      expect(payload.prescriptionNumber).toBe("RX-2026-0099");
      expect(payload.prescriberIdNumber).toBe("CC-123456789");
      expect(payload.prescriberName).toBe("Dr. Carlos López");
    });
  });

  describe("metadata — local audit data", () => {
    it("includes userId identifying the verifying operator", () => {
      const payload = makePosPayload();
      expect(typeof payload.metadata.userId).toBe("string");
      expect(payload.metadata.userId.length).toBeGreaterThan(0);
    });

    it("includes workstation identifier", () => {
      const payload = makePosPayload();
      expect(payload.metadata.workstationId).toBe("ws-001");
    });

    it("includes createdAt in ISO-8601 format", () => {
      const payload = makePosPayload();
      expect(payload.metadata.createdAt).toMatch(ISO_DATETIME_RE);
    });
  });

  describe("SyncOperationSchema envelope", () => {
    it("conforms to the server's envelope format", () => {
      const envelope = {
        operationType: "PRESCRIPTION_REGISTRATION",
        operationUuid: "c3d4e5f6-a7b8-9012-cdef-123456789012",
        payload: makePosPayload() as unknown as Record<string, unknown>,
        payloadHash:
          "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
        sourceCreatedAt: "2026-07-16T10:00:00.000Z",
        clientSequence: 8,
      };

      expect(() => assertEnvelope(envelope)).not.toThrow();
    });

    it("rejects an invalid operation type", () => {
      expect(() =>
        assertEnvelope({
          operationType: "INVALID_TYPE",
          operationUuid: "c3d4e5f6-a7b8-9012-cdef-123456789012",
          payload: {},
          payloadHash: "abc",
          sourceCreatedAt: "2026-07-16T10:00:00.000Z",
          clientSequence: 1,
        }),
      ).toThrow();
    });
  });
});
